const fs = require("fs");
const pptx = require("pptxgenjs");

const ppt_doc_1 = new pptx();
const ppt_doc_1_debug = { defaultStyle: {}, styles: {}, slides: [] };
const defaultStyle = { content: {} };
const styles = {};
const ppt_defaultStyleDef_2 = {};
ppt_defaultStyleDef_2.fontFace = "Tahoma";
ppt_defaultStyleDef_2.fontSize = 12;
ppt_defaultStyleDef_2.valign = "middle";
defaultStyle.content = ppt_defaultStyleDef_2;
ppt_doc_1_debug.defaultStyle = ppt_defaultStyleDef_2;
const ppt_styleDef_3 = {};
ppt_styleDef_3.fontSize = 60;
ppt_styleDef_3.x = "25%";
ppt_styleDef_3.w ="65%";
ppt_styleDef_3.bold = true;
styles[".forefront-title"] = ppt_styleDef_3;
ppt_doc_1_debug.styles[".forefront-title"] = ppt_styleDef_3;
const ppt_styleDef_4 = {};
ppt_styleDef_4.fontSize = 40;
ppt_styleDef_4.x = "25%";
ppt_styleDef_4.w ="65%";
ppt_styleDef_4.italic = true;
styles[".forefront-subtitle"] = ppt_styleDef_4;
ppt_doc_1_debug.styles[".forefront-subtitle"] = ppt_styleDef_4;
const ppt_styleDef_5 = {};
ppt_styleDef_5.fontSize = 15;
ppt_styleDef_5.x = "25%";
ppt_styleDef_5.w ="65%";
styles[".forefront-author"] = ppt_styleDef_5;
ppt_doc_1_debug.styles[".forefront-author"] = ppt_styleDef_5;
const ppt_styleDef_6 = {};
ppt_styleDef_6.fontSize = 10;
ppt_styleDef_6.x = "25%";
ppt_styleDef_6.w ="65%";
ppt_styleDef_6.italic = true;
styles[".forefront-date"] = ppt_styleDef_6;
ppt_doc_1_debug.styles[".forefront-date"] = ppt_styleDef_6;
const ppt_styleDef_7 = {};
ppt_styleDef_7.fontSize = 40;
ppt_styleDef_7.x = "30%";
ppt_styleDef_7.y = "8%";
ppt_styleDef_7.w ="70%";
ppt_styleDef_7.x = "20%";
ppt_styleDef_7.bold = true;
ppt_styleDef_7.color = "#e02424";
ppt_styleDef_7.align = "right";
styles["titolo1"] = ppt_styleDef_7;
ppt_doc_1_debug.styles["titolo1"] = ppt_styleDef_7;
const ppt_styleDef_8 = {};
ppt_styleDef_8.fontSize = 30;
ppt_styleDef_8.x = "10%";
ppt_styleDef_8.y = "12%";
ppt_styleDef_8.w ="50%";
ppt_styleDef_8.x = "8%";
ppt_styleDef_8.bold = true;
ppt_styleDef_8.italic = true;
ppt_styleDef_8.color = "#020202";
ppt_styleDef_8.align = "left";
styles["titolo2"] = ppt_styleDef_8;
ppt_doc_1_debug.styles["titolo2"] = ppt_styleDef_8;
const ppt_styleDef_9 = {};
ppt_styleDef_9.fontSize = 15;
ppt_styleDef_9.align = "left";
styles["para1"] = ppt_styleDef_9;
ppt_doc_1_debug.styles["para1"] = ppt_styleDef_9;
const ppt_styleDef_10 = {};
ppt_styleDef_10.fontSize = 37.5;
ppt_styleDef_10.align = "left";
ppt_styleDef_10.x = "20%";
styles["para1big"] = ppt_styleDef_10;
ppt_doc_1_debug.styles["para1big"] = ppt_styleDef_10;
const ppt_styleDef_11 = {};
styles[".cite-reviews"] = ppt_styleDef_11;
ppt_doc_1_debug.styles[".cite-reviews"] = ppt_styleDef_11;
const ppt_styleDef_12 = {};
ppt_styleDef_12.fontSize = 10;
ppt_styleDef_12.align = "left";
ppt_styleDef_12.x = "20%";
ppt_styleDef_12.bold = true;
styles[".cite-article"] = ppt_styleDef_12;
ppt_doc_1_debug.styles[".cite-article"] = ppt_styleDef_12;
const ppt_styleDef_13 = {};
ppt_styleDef_13.fontSize = 10;
ppt_styleDef_13.italic = true;
ppt_styleDef_13.align = "left";
ppt_styleDef_13.x = "20%";
styles[".cite-authors"] = ppt_styleDef_13;
ppt_doc_1_debug.styles[".cite-authors"] = ppt_styleDef_13;
const ppt_styleDef_14 = {};
ppt_styleDef_14.fontSize = 10;
ppt_styleDef_14.italic = true;
ppt_styleDef_14.align = "left";
styles[".cite-review"] = ppt_styleDef_14;
ppt_doc_1_debug.styles[".cite-review"] = ppt_styleDef_14;
const ppt_styleDef_15 = {};
ppt_styleDef_15.fontSize = 60;
ppt_styleDef_15.align = "center";
ppt_styleDef_15.color = "#e02424";
ppt_styleDef_15.bold = true;
ppt_styleDef_15.x = "20%";
ppt_styleDef_15.w ="60%";
styles[".thanks-title"] = ppt_styleDef_15;
ppt_doc_1_debug.styles[".thanks-title"] = ppt_styleDef_15;
const ppt_styleDef_16 = {};
ppt_styleDef_16.fontSize = 48;
ppt_styleDef_16.align = "center";
ppt_styleDef_16.color = "#e02424";
ppt_styleDef_16.bold = true;
ppt_styleDef_16.x = "20%";
ppt_styleDef_16.w ="60%";
styles[".thanks-subtitle"] = ppt_styleDef_16;
ppt_doc_1_debug.styles[".thanks-subtitle"] = ppt_styleDef_16;
const ppt_styleDef_17 = {};
ppt_styleDef_17.fontSize = 16;
ppt_styleDef_17.bold = true;
styles[".column-title"] = ppt_styleDef_17;
ppt_doc_1_debug.styles[".column-title"] = ppt_styleDef_17;
const ppt_styleDef_18 = {};
ppt_styleDef_18.fontSize = 14;
styles[".column-p"] = ppt_styleDef_18;
ppt_doc_1_debug.styles[".column-p"] = ppt_styleDef_18;
const ppt_styleDef_19 = {};
ppt_styleDef_19.fontSize = 28;
styles[".column-p-big"] = ppt_styleDef_19;
ppt_doc_1_debug.styles[".column-p-big"] = ppt_styleDef_19;
const ppt_slide_20 = ppt_doc_1.addSlide();
const ppt_slide_20_debug = { items: [] };
var ppt_p_21 = Object.assign({}, defaultStyle.content);
const ppt_p_21_text = "Le guide anticipatorie";
ppt_p_21 = Object.assign({},ppt_p_21, (styles[".forefront-title"] || {}));
ppt_p_21.y = "25%";
ppt_p_21.isTextBox = true;
ppt_slide_20.addText(ppt_p_21_text, ppt_p_21);
ppt_slide_20_debug.items.push({ text: ppt_p_21_text, options: ppt_p_21 });
var ppt_p_22 = Object.assign({}, defaultStyle.content);
const ppt_p_22_text = "Tutti a tavola";
ppt_p_22 = Object.assign({},ppt_p_22, (styles[".forefront-subtitle"] || {}));
ppt_p_22.y = "45%";
ppt_p_22.isTextBox = true;
ppt_slide_20.addText(ppt_p_22_text, ppt_p_22);
ppt_slide_20_debug.items.push({ text: ppt_p_22_text, options: ppt_p_22 });
var ppt_p_23 = Object.assign({}, defaultStyle.content);
const ppt_p_23_text = "Nati per leggere";
ppt_p_23 = Object.assign({},ppt_p_23, (styles[".forefront-subtitle"] || {}));
ppt_p_23.y = "60%";
ppt_p_23.isTextBox = true;
ppt_slide_20.addText(ppt_p_23_text, ppt_p_23);
ppt_slide_20_debug.items.push({ text: ppt_p_23_text, options: ppt_p_23 });
var ppt_p_24 = Object.assign({}, defaultStyle.content);
const ppt_p_24_text = "Anna Maria Davoli";
ppt_p_24 = Object.assign({},ppt_p_24, (styles[".forefront-author"] || {}));
ppt_p_24.y = "75%";
ppt_p_24.isTextBox = true;
ppt_slide_20.addText(ppt_p_24_text, ppt_p_24);
ppt_slide_20_debug.items.push({ text: ppt_p_24_text, options: ppt_p_24 });
var ppt_p_25 = Object.assign({}, defaultStyle.content);
const ppt_p_25_text = "17 marzo 2021";
ppt_p_25 = Object.assign({},ppt_p_25, (styles[".forefront-date"] || {}));
ppt_p_25.y = "80%";
ppt_p_25.isTextBox = true;
ppt_slide_20.addText(ppt_p_25_text, ppt_p_25);
ppt_slide_20_debug.items.push({ text: ppt_p_25_text, options: ppt_p_25 });
ppt_doc_1_debug.slides.push(ppt_slide_20_debug);
const ppt_slide_26 = ppt_doc_1.addSlide();
const ppt_slide_26_debug = { items: [] };
var ppt_p_27 = Object.assign({}, defaultStyle.content);
const ppt_p_27_text = "";
ppt_p_27 = Object.assign({},ppt_p_27, (styles["titolo1"] || {}));
ppt_p_27.isTextBox = true;
ppt_slide_26.addText(ppt_p_27_text, ppt_p_27);
ppt_slide_26_debug.items.push({ text: ppt_p_27_text, options: ppt_p_27 });
var ppt_p_28 = Object.assign({}, defaultStyle.content);
const ppt_p_28_text = "Le App a supporto di genitori e caregiver";
ppt_p_28 = Object.assign({},ppt_p_28, (styles["titolo2"] || {}));
ppt_p_28.isTextBox = true;
ppt_slide_26.addText(ppt_p_28_text, ppt_p_28);
ppt_slide_26_debug.items.push({ text: ppt_p_28_text, options: ppt_p_28 });
var ppt_p_29 = Object.assign({}, defaultStyle.content);
const ppt_p_29_text = "Contenuti basati sulle evidenze";
ppt_p_29 = Object.assign({},ppt_p_29, (styles["para1"] || {}));
const ppt_bulletObj_30 = {};
ppt_bulletObj_30.indent = 6;
ppt_bulletObj_30.code = "2B24";
ppt_p_29.bullet = ppt_bulletObj_30;
ppt_p_29.x = "10%";
ppt_p_29.y = "48%";
ppt_p_29.w ="80%";
ppt_p_29.isTextBox = true;
ppt_slide_26.addText(ppt_p_29_text, ppt_p_29);
ppt_slide_26_debug.items.push({ text: ppt_p_29_text, options: ppt_p_29 });
var ppt_p_31 = Object.assign({}, defaultStyle.content);
const ppt_p_31_text = "Informazioni coerenti con le linee guida";
ppt_p_31 = Object.assign({},ppt_p_31, (styles["para1"] || {}));
const ppt_bulletObj_32 = {};
ppt_bulletObj_32.indent = 6;
ppt_bulletObj_32.code = "2B24";
ppt_p_31.bullet = ppt_bulletObj_32;
ppt_p_31.x = "10%";
ppt_p_31.y = "58%";
ppt_p_31.w ="80%";
ppt_p_31.isTextBox = true;
ppt_slide_26.addText(ppt_p_31_text, ppt_p_31);
ppt_slide_26_debug.items.push({ text: ppt_p_31_text, options: ppt_p_31 });
var ppt_p_33 = Object.assign({}, defaultStyle.content);
const ppt_p_33_text = "Sviluppate con il supporto di professionisti sanitari";
ppt_p_33 = Object.assign({},ppt_p_33, (styles["para1"] || {}));
const ppt_bulletObj_34 = {};
ppt_bulletObj_34.indent = 6;
ppt_bulletObj_34.code = "2B24";
ppt_p_33.bullet = ppt_bulletObj_34;
ppt_p_33.x = "10%";
ppt_p_33.y = "68%";
ppt_p_33.w ="80%";
ppt_p_33.isTextBox = true;
ppt_slide_26.addText(ppt_p_33_text, ppt_p_33);
ppt_slide_26_debug.items.push({ text: ppt_p_33_text, options: ppt_p_33 });
var ppt_p_35 = Object.assign({}, defaultStyle.content);
const ppt_p_35_text = "Con finanziamento adeguato (del Servizio Sanitario)";
ppt_p_35 = Object.assign({},ppt_p_35, (styles["para1"] || {}));
const ppt_bulletObj_36 = {};
ppt_bulletObj_36.indent = 6;
ppt_bulletObj_36.code = "2B24";
ppt_p_35.bullet = ppt_bulletObj_36;
ppt_p_35.x = "10%";
ppt_p_35.y = "78%";
ppt_p_35.w ="80%";
ppt_p_35.isTextBox = true;
ppt_slide_26.addText(ppt_p_35_text, ppt_p_35);
ppt_slide_26_debug.items.push({ text: ppt_p_35_text, options: ppt_p_35 });
var ppt_p_37 = Object.assign({}, defaultStyle.content);
const ppt_p_37_text = "Garantiscono che ai genitori vengano fornite risorse credibili e affidabili.";
ppt_p_37 = Object.assign({},ppt_p_37, (styles["para1"] || {}));
ppt_p_37.x = "10%";
ppt_p_37.y = "88%";
ppt_p_37.w ="80%";
ppt_p_37.isTextBox = true;
ppt_slide_26.addText(ppt_p_37_text, ppt_p_37);
ppt_slide_26_debug.items.push({ text: ppt_p_37_text, options: ppt_p_37 });
const ppt_pStack_38 = [];
const ppt_pStack_38_items = [];
var ppt_p_39 = Object.assign({}, defaultStyle.content);
const ppt_p_39_text = "Content and Quality of Infant Feeding Smartphone Apps: Five-Year Update on a Systematic Search and Evaluation";
ppt_p_39 = Object.assign({},ppt_p_39, (styles[".cite-article"] || {}));
ppt_p_39.x = "10%";
ppt_p_39.y = "98%";
ppt_p_39.w ="80%";
ppt_pStack_38_items.push({ text: ppt_p_39_text, options: ppt_p_39 });
var ppt_p_40 = Object.assign({}, defaultStyle.content);
const ppt_p_40_text = "Heilok Cheng, et all";
ppt_p_40 = Object.assign({},ppt_p_40, (styles[".cite-authors"] || {}));
ppt_p_40.x = "10%";
ppt_p_40.y = "104%";
ppt_p_40.w ="80%";
ppt_pStack_38_items.push({ text: ppt_p_40_text, options: ppt_p_40 });
var ppt_p_41 = Object.assign({}, defaultStyle.content);
const ppt_p_41_text = "A Mobile App, KhunLook, to Support Thai Parents and Caregivers With Child Health Supervision: Development, Validation, and Acceptability Study";
ppt_p_41 = Object.assign({},ppt_p_41, (styles[".cite-article"] || {}));
ppt_p_41.x = "10%";
ppt_p_41.y = "110%";
ppt_p_41.w ="80%";
ppt_pStack_38_items.push({ text: ppt_p_41_text, options: ppt_p_41 });
var ppt_p_42 = Object.assign({}, defaultStyle.content);
const ppt_p_42_text = "Rosawan Areemit";
ppt_p_42 = Object.assign({},ppt_p_42, (styles[".cite-authors"] || {}));
ppt_p_42.x = "10%";
ppt_p_42.y = "116%";
ppt_p_42.w ="80%";
ppt_pStack_38_items.push({ text: ppt_p_42_text, options: ppt_p_42 });
ppt_pStack_38.isTextBox = true;
ppt_slide_26.addText(ppt_pStack_38_items, ppt_pStack_38);
ppt_slide_26_debug.items.push({ pStack: ppt_pStack_38_items, options: ppt_pStack_38 });
ppt_doc_1_debug.slides.push(ppt_slide_26_debug);
const ppt_slide_43 = ppt_doc_1.addSlide();
const ppt_slide_43_debug = { items: [] };
var ppt_p_44 = Object.assign({}, defaultStyle.content);
const ppt_p_44_text = "";
ppt_p_44 = Object.assign({},ppt_p_44, (styles["titolo1"] || {}));
ppt_p_44.isTextBox = true;
ppt_slide_43.addText(ppt_p_44_text, ppt_p_44);
ppt_slide_43_debug.items.push({ text: ppt_p_44_text, options: ppt_p_44 });
var ppt_p_45 = Object.assign({}, defaultStyle.content);
const ppt_p_45_text = "Una App aiuta i genitori?";
ppt_p_45 = Object.assign({},ppt_p_45, (styles["titolo2"] || {}));
ppt_p_45.isTextBox = true;
ppt_slide_43.addText(ppt_p_45_text, ppt_p_45);
ppt_slide_43_debug.items.push({ text: ppt_p_45_text, options: ppt_p_45 });
var ppt_p_46 = Object.assign({}, defaultStyle.content);
const ppt_p_46_text = "I genitori apprezzano le mHealth Apps.";
ppt_p_46 = Object.assign({},ppt_p_46, (styles["para1"] || {}));
ppt_p_46.x = "10%";
ppt_p_46.y = "48%";
ppt_p_46.w ="80%";
ppt_p_46.isTextBox = true;
ppt_slide_43.addText(ppt_p_46_text, ppt_p_46);
ppt_slide_43_debug.items.push({ text: ppt_p_46_text, options: ppt_p_46 });
var ppt_p_47 = Object.assign({}, defaultStyle.content);
const ppt_p_47_text = "Richiedono contatti brevi e ripetuti con informazioni pratiche.";
ppt_p_47 = Object.assign({},ppt_p_47, (styles["para1"] || {}));
ppt_p_47.x = "10%";
ppt_p_47.y = "58%";
ppt_p_47.w ="80%";
ppt_p_47.isTextBox = true;
ppt_slide_43.addText(ppt_p_47_text, ppt_p_47);
ppt_slide_43_debug.items.push({ text: ppt_p_47_text, options: ppt_p_47 });
var ppt_p_48 = Object.assign({}, defaultStyle.content);
const ppt_p_48_text = "Un programma eHealth di prevenzione dell'obesità infantile incentrato sui genitori può fornire supporto per migliorare l'alimentazione del bambino e l'autoefficacia parentale.";
ppt_p_48 = Object.assign({},ppt_p_48, (styles["para1"] || {}));
ppt_p_48.x = "10%";
ppt_p_48.y = "68%";
ppt_p_48.w ="80%";
ppt_p_48.isTextBox = true;
ppt_slide_43.addText(ppt_p_48_text, ppt_p_48);
ppt_slide_43_debug.items.push({ text: ppt_p_48_text, options: ppt_p_48 });
const ppt_pStack_49 = [];
const ppt_pStack_49_items = [];
var ppt_p_50 = Object.assign({}, defaultStyle.content);
const ppt_p_50_text = "A Mobile App, KhunLook, to Support Thai Parents and Caregivers With Child Health Supervision: Development, Validation, and Acceptability Study";
ppt_p_50 = Object.assign({},ppt_p_50, (styles[".cite-article"] || {}));
ppt_p_50.x = "10%";
ppt_p_50.y = "78%";
ppt_p_50.w ="80%";
ppt_pStack_49_items.push({ text: ppt_p_50_text, options: ppt_p_50 });
var ppt_p_51 = Object.assign({}, defaultStyle.content);
const ppt_p_51_text = "Rosawan Areemit et all";
ppt_p_51 = Object.assign({},ppt_p_51, (styles[".cite-authors"] || {}));
ppt_p_51.x = "10%";
ppt_p_51.y = "84%";
ppt_p_51.w ="80%";
ppt_pStack_49_items.push({ text: ppt_p_51_text, options: ppt_p_51 });
var ppt_p_52 = Object.assign({}, defaultStyle.content);
const ppt_p_52_text = "An Internet-Based Childhood Obesity Prevention Program (Time2bHealthy) for Parents of Preschool-Aged Children.";
ppt_p_52 = Object.assign({},ppt_p_52, (styles[".cite-article"] || {}));
ppt_p_52.x = "10%";
ppt_p_52.y = "90%";
ppt_p_52.w ="80%";
ppt_pStack_49_items.push({ text: ppt_p_52_text, options: ppt_p_52 });
var ppt_p_53 = Object.assign({}, defaultStyle.content);
const ppt_p_53_text = "Megan L Hammersley et all";
ppt_p_53 = Object.assign({},ppt_p_53, (styles[".cite-authors"] || {}));
ppt_p_53.x = "10%";
ppt_p_53.y = "96%";
ppt_p_53.w ="80%";
ppt_pStack_49_items.push({ text: ppt_p_53_text, options: ppt_p_53 });
var ppt_p_54 = Object.assign({}, defaultStyle.content);
const ppt_p_54_text = "Randomized Controlled Trial J Med Internet Res, 2019 Feb 8;21(2):e11964. Doi: 10.2196/11964.";
ppt_p_54 = Object.assign({},ppt_p_54, (styles[".cite-review"] || {}));
ppt_p_54.x = "10%";
ppt_p_54.y = "102%";
ppt_p_54.w ="80%";
ppt_pStack_49_items.push({ text: ppt_p_54_text, options: ppt_p_54 });
var ppt_p_55 = Object.assign({}, defaultStyle.content);
const ppt_p_55_text = "A systematic evaluation of digital nutrition promotion websites and apps for supporting parents to influence children’s nutrition";
ppt_p_55 = Object.assign({},ppt_p_55, (styles[".cite-article"] || {}));
ppt_p_55.x = "10%";
ppt_p_55.y = "108%";
ppt_p_55.w ="80%";
ppt_pStack_49_items.push({ text: ppt_p_55_text, options: ppt_p_55 });
var ppt_p_56 = Object.assign({}, defaultStyle.content);
const ppt_p_56_text = "Dorota Zarnowiecki, et all";
ppt_p_56 = Object.assign({},ppt_p_56, (styles[".cite-authors"] || {}));
ppt_p_56.x = "10%";
ppt_p_56.y = "114%";
ppt_p_56.w ="80%";
ppt_pStack_49_items.push({ text: ppt_p_56_text, options: ppt_p_56 });
var ppt_p_57 = Object.assign({}, defaultStyle.content);
const ppt_p_57_text = "International Journal of Behavioral Nutrition and Physical Activity volume 17, Article number: 17 (2020)";
ppt_p_57 = Object.assign({},ppt_p_57, (styles[".cite-review"] || {}));
ppt_p_57.x = "10%";
ppt_p_57.y = "120%";
ppt_p_57.w ="80%";
ppt_pStack_49_items.push({ text: ppt_p_57_text, options: ppt_p_57 });
ppt_pStack_49.isTextBox = true;
ppt_slide_43.addText(ppt_pStack_49_items, ppt_pStack_49);
ppt_slide_43_debug.items.push({ pStack: ppt_pStack_49_items, options: ppt_pStack_49 });
ppt_doc_1_debug.slides.push(ppt_slide_43_debug);
const ppt_slide_58 = ppt_doc_1.addSlide();
const ppt_slide_58_debug = { items: [] };
var ppt_p_59 = Object.assign({}, defaultStyle.content);
const ppt_p_59_text = "Tutti a tavola";
ppt_p_59 = Object.assign({},ppt_p_59, (styles["titolo1"] || {}));
ppt_p_59.isTextBox = true;
ppt_slide_58.addText(ppt_p_59_text, ppt_p_59);
ppt_slide_58_debug.items.push({ text: ppt_p_59_text, options: ppt_p_59 });
var ppt_p_60 = Object.assign({}, defaultStyle.content);
const ppt_p_60_text = "nascita";
ppt_p_60 = Object.assign({},ppt_p_60, (styles["titolo2"] || {}));
ppt_p_60.isTextBox = true;
ppt_slide_58.addText(ppt_p_60_text, ppt_p_60);
ppt_slide_58_debug.items.push({ text: ppt_p_60_text, options: ppt_p_60 });
const ppt_image_61 = {};
ppt_image_61.path = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/nascita.png";
ppt_image_61.x = "20%";
ppt_image_61.y = "24%";
ppt_image_61.w ="25%";
ppt_image_61.h ="65%";
ppt_slide_58.addImage(ppt_image_61);
ppt_slide_58_debug.items.push({ image: ppt_image_61 });
ppt_doc_1_debug.slides.push(ppt_slide_58_debug);
const ppt_slide_62 = ppt_doc_1.addSlide();
const ppt_slide_62_debug = { items: [] };
var ppt_p_63 = Object.assign({}, defaultStyle.content);
const ppt_p_63_text = "Tutti a tavola";
ppt_p_63 = Object.assign({},ppt_p_63, (styles["titolo1"] || {}));
ppt_p_63.isTextBox = true;
ppt_slide_62.addText(ppt_p_63_text, ppt_p_63);
ppt_slide_62_debug.items.push({ text: ppt_p_63_text, options: ppt_p_63 });
var ppt_p_64 = Object.assign({}, defaultStyle.content);
const ppt_p_64_text = "15 giorni";
ppt_p_64 = Object.assign({},ppt_p_64, (styles["titolo2"] || {}));
ppt_p_64.isTextBox = true;
ppt_slide_62.addText(ppt_p_64_text, ppt_p_64);
ppt_slide_62_debug.items.push({ text: ppt_p_64_text, options: ppt_p_64 });
const ppt_image_65 = {};
ppt_image_65.path = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/15 giorni.png";
ppt_image_65.x = "20%";
ppt_image_65.y = "24%";
ppt_image_65.w ="25%";
ppt_image_65.h ="65%";
ppt_slide_62.addImage(ppt_image_65);
ppt_slide_62_debug.items.push({ image: ppt_image_65 });
ppt_doc_1_debug.slides.push(ppt_slide_62_debug);
const ppt_slide_66 = ppt_doc_1.addSlide();
const ppt_slide_66_debug = { items: [] };
var ppt_p_67 = Object.assign({}, defaultStyle.content);
const ppt_p_67_text = "Tutti a tavola";
ppt_p_67 = Object.assign({},ppt_p_67, (styles["titolo1"] || {}));
ppt_p_67.isTextBox = true;
ppt_slide_66.addText(ppt_p_67_text, ppt_p_67);
ppt_slide_66_debug.items.push({ text: ppt_p_67_text, options: ppt_p_67 });
var ppt_p_68 = Object.assign({}, defaultStyle.content);
const ppt_p_68_text = "1 mese";
ppt_p_68 = Object.assign({},ppt_p_68, (styles["titolo2"] || {}));
ppt_p_68.isTextBox = true;
ppt_slide_66.addText(ppt_p_68_text, ppt_p_68);
ppt_slide_66_debug.items.push({ text: ppt_p_68_text, options: ppt_p_68 });
const ppt_image_69 = {};
ppt_image_69.path = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/1 mese.png";
ppt_image_69.x = "20%";
ppt_image_69.y = "24%";
ppt_image_69.w ="25%";
ppt_image_69.h ="65%";
ppt_slide_66.addImage(ppt_image_69);
ppt_slide_66_debug.items.push({ image: ppt_image_69 });
ppt_doc_1_debug.slides.push(ppt_slide_66_debug);
const ppt_slide_70 = ppt_doc_1.addSlide();
const ppt_slide_70_debug = { items: [] };
var ppt_p_71 = Object.assign({}, defaultStyle.content);
const ppt_p_71_text = "Tutti a tavola";
ppt_p_71 = Object.assign({},ppt_p_71, (styles["titolo1"] || {}));
ppt_p_71.isTextBox = true;
ppt_slide_70.addText(ppt_p_71_text, ppt_p_71);
ppt_slide_70_debug.items.push({ text: ppt_p_71_text, options: ppt_p_71 });
var ppt_p_72 = Object.assign({}, defaultStyle.content);
const ppt_p_72_text = "5 mesi";
ppt_p_72 = Object.assign({},ppt_p_72, (styles["titolo2"] || {}));
ppt_p_72.isTextBox = true;
ppt_slide_70.addText(ppt_p_72_text, ppt_p_72);
ppt_slide_70_debug.items.push({ text: ppt_p_72_text, options: ppt_p_72 });
const ppt_image_73 = {};
ppt_image_73.path = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/5 mesi.png";
ppt_image_73.x = "20%";
ppt_image_73.y = "24%";
ppt_image_73.w ="25%";
ppt_image_73.h ="65%";
ppt_slide_70.addImage(ppt_image_73);
ppt_slide_70_debug.items.push({ image: ppt_image_73 });
ppt_doc_1_debug.slides.push(ppt_slide_70_debug);
const ppt_slide_74 = ppt_doc_1.addSlide();
const ppt_slide_74_debug = { items: [] };
var ppt_p_75 = Object.assign({}, defaultStyle.content);
const ppt_p_75_text = "Tutti a tavola";
ppt_p_75 = Object.assign({},ppt_p_75, (styles["titolo1"] || {}));
ppt_p_75.isTextBox = true;
ppt_slide_74.addText(ppt_p_75_text, ppt_p_75);
ppt_slide_74_debug.items.push({ text: ppt_p_75_text, options: ppt_p_75 });
var ppt_p_76 = Object.assign({}, defaultStyle.content);
const ppt_p_76_text = "6 mesi";
ppt_p_76 = Object.assign({},ppt_p_76, (styles["titolo2"] || {}));
ppt_p_76.isTextBox = true;
ppt_slide_74.addText(ppt_p_76_text, ppt_p_76);
ppt_slide_74_debug.items.push({ text: ppt_p_76_text, options: ppt_p_76 });
const ppt_image_77 = {};
ppt_image_77.path = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/6 mesi.png";
ppt_image_77.x = "20%";
ppt_image_77.y = "24%";
ppt_image_77.w ="25%";
ppt_image_77.h ="65%";
ppt_slide_74.addImage(ppt_image_77);
ppt_slide_74_debug.items.push({ image: ppt_image_77 });
ppt_doc_1_debug.slides.push(ppt_slide_74_debug);
const ppt_slide_78 = ppt_doc_1.addSlide();
const ppt_slide_78_debug = { items: [] };
var ppt_p_79 = Object.assign({}, defaultStyle.content);
const ppt_p_79_text = "Tutti a tavola";
ppt_p_79 = Object.assign({},ppt_p_79, (styles["titolo1"] || {}));
ppt_p_79.isTextBox = true;
ppt_slide_78.addText(ppt_p_79_text, ppt_p_79);
ppt_slide_78_debug.items.push({ text: ppt_p_79_text, options: ppt_p_79 });
var ppt_p_80 = Object.assign({}, defaultStyle.content);
const ppt_p_80_text = "9 mesi/1";
ppt_p_80 = Object.assign({},ppt_p_80, (styles["titolo2"] || {}));
ppt_p_80.isTextBox = true;
ppt_slide_78.addText(ppt_p_80_text, ppt_p_80);
ppt_slide_78_debug.items.push({ text: ppt_p_80_text, options: ppt_p_80 });
const ppt_image_81 = {};
ppt_image_81.path = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/9 mesi 1.png";
ppt_image_81.x = "20%";
ppt_image_81.y = "24%";
ppt_image_81.w ="25%";
ppt_image_81.h ="65%";
ppt_slide_78.addImage(ppt_image_81);
ppt_slide_78_debug.items.push({ image: ppt_image_81 });
ppt_doc_1_debug.slides.push(ppt_slide_78_debug);
const ppt_slide_82 = ppt_doc_1.addSlide();
const ppt_slide_82_debug = { items: [] };
var ppt_p_83 = Object.assign({}, defaultStyle.content);
const ppt_p_83_text = "Tutti a tavola";
ppt_p_83 = Object.assign({},ppt_p_83, (styles["titolo1"] || {}));
ppt_p_83.isTextBox = true;
ppt_slide_82.addText(ppt_p_83_text, ppt_p_83);
ppt_slide_82_debug.items.push({ text: ppt_p_83_text, options: ppt_p_83 });
var ppt_p_84 = Object.assign({}, defaultStyle.content);
const ppt_p_84_text = "9 mesi/2";
ppt_p_84 = Object.assign({},ppt_p_84, (styles["titolo2"] || {}));
ppt_p_84.isTextBox = true;
ppt_slide_82.addText(ppt_p_84_text, ppt_p_84);
ppt_slide_82_debug.items.push({ text: ppt_p_84_text, options: ppt_p_84 });
const ppt_image_85 = {};
ppt_image_85.path = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/9 mesi 2.png";
ppt_image_85.x = "20%";
ppt_image_85.y = "24%";
ppt_image_85.w ="25%";
ppt_image_85.h ="65%";
ppt_slide_82.addImage(ppt_image_85);
ppt_slide_82_debug.items.push({ image: ppt_image_85 });
ppt_doc_1_debug.slides.push(ppt_slide_82_debug);
const ppt_slide_86 = ppt_doc_1.addSlide();
const ppt_slide_86_debug = { items: [] };
var ppt_p_87 = Object.assign({}, defaultStyle.content);
const ppt_p_87_text = "Tutti a tavola";
ppt_p_87 = Object.assign({},ppt_p_87, (styles["titolo1"] || {}));
ppt_p_87.isTextBox = true;
ppt_slide_86.addText(ppt_p_87_text, ppt_p_87);
ppt_slide_86_debug.items.push({ text: ppt_p_87_text, options: ppt_p_87 });
var ppt_p_88 = Object.assign({}, defaultStyle.content);
const ppt_p_88_text = "1 anno";
ppt_p_88 = Object.assign({},ppt_p_88, (styles["titolo2"] || {}));
ppt_p_88.isTextBox = true;
ppt_slide_86.addText(ppt_p_88_text, ppt_p_88);
ppt_slide_86_debug.items.push({ text: ppt_p_88_text, options: ppt_p_88 });
const ppt_image_89 = {};
ppt_image_89.path = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/1 anno.png";
ppt_image_89.x = "20%";
ppt_image_89.y = "24%";
ppt_image_89.w ="25%";
ppt_image_89.h ="65%";
ppt_slide_86.addImage(ppt_image_89);
ppt_slide_86_debug.items.push({ image: ppt_image_89 });
ppt_doc_1_debug.slides.push(ppt_slide_86_debug);
const ppt_slide_90 = ppt_doc_1.addSlide();
const ppt_slide_90_debug = { items: [] };
var ppt_p_91 = Object.assign({}, defaultStyle.content);
const ppt_p_91_text = "Tutti a tavola";
ppt_p_91 = Object.assign({},ppt_p_91, (styles["titolo1"] || {}));
ppt_p_91.isTextBox = true;
ppt_slide_90.addText(ppt_p_91_text, ppt_p_91);
ppt_slide_90_debug.items.push({ text: ppt_p_91_text, options: ppt_p_91 });
var ppt_p_92 = Object.assign({}, defaultStyle.content);
const ppt_p_92_text = "14 mesi";
ppt_p_92 = Object.assign({},ppt_p_92, (styles["titolo2"] || {}));
ppt_p_92.isTextBox = true;
ppt_slide_90.addText(ppt_p_92_text, ppt_p_92);
ppt_slide_90_debug.items.push({ text: ppt_p_92_text, options: ppt_p_92 });
const ppt_image_93 = {};
ppt_image_93.path = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/14 mesi.png";
ppt_image_93.x = "20%";
ppt_image_93.y = "24%";
ppt_image_93.w ="25%";
ppt_image_93.h ="65%";
ppt_slide_90.addImage(ppt_image_93);
ppt_slide_90_debug.items.push({ image: ppt_image_93 });
ppt_doc_1_debug.slides.push(ppt_slide_90_debug);
const ppt_slide_94 = ppt_doc_1.addSlide();
const ppt_slide_94_debug = { items: [] };
var ppt_p_95 = Object.assign({}, defaultStyle.content);
const ppt_p_95_text = "Tutti a tavola";
ppt_p_95 = Object.assign({},ppt_p_95, (styles["titolo1"] || {}));
ppt_p_95.isTextBox = true;
ppt_slide_94.addText(ppt_p_95_text, ppt_p_95);
ppt_slide_94_debug.items.push({ text: ppt_p_95_text, options: ppt_p_95 });
var ppt_p_96 = Object.assign({}, defaultStyle.content);
const ppt_p_96_text = "17 mesi 1";
ppt_p_96 = Object.assign({},ppt_p_96, (styles["titolo2"] || {}));
ppt_p_96.isTextBox = true;
ppt_slide_94.addText(ppt_p_96_text, ppt_p_96);
ppt_slide_94_debug.items.push({ text: ppt_p_96_text, options: ppt_p_96 });
const ppt_image_97 = {};
ppt_image_97.path = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/17 m 1.png";
ppt_image_97.x = "20%";
ppt_image_97.y = "24%";
ppt_image_97.w ="25%";
ppt_image_97.h ="65%";
ppt_slide_94.addImage(ppt_image_97);
ppt_slide_94_debug.items.push({ image: ppt_image_97 });
ppt_doc_1_debug.slides.push(ppt_slide_94_debug);
const ppt_slide_98 = ppt_doc_1.addSlide();
const ppt_slide_98_debug = { items: [] };
var ppt_p_99 = Object.assign({}, defaultStyle.content);
const ppt_p_99_text = "Tutti a tavola";
ppt_p_99 = Object.assign({},ppt_p_99, (styles["titolo1"] || {}));
ppt_p_99.isTextBox = true;
ppt_slide_98.addText(ppt_p_99_text, ppt_p_99);
ppt_slide_98_debug.items.push({ text: ppt_p_99_text, options: ppt_p_99 });
var ppt_p_100 = Object.assign({}, defaultStyle.content);
const ppt_p_100_text = "17 mesi 2";
ppt_p_100 = Object.assign({},ppt_p_100, (styles["titolo2"] || {}));
ppt_p_100.isTextBox = true;
ppt_slide_98.addText(ppt_p_100_text, ppt_p_100);
ppt_slide_98_debug.items.push({ text: ppt_p_100_text, options: ppt_p_100 });
const ppt_image_101 = {};
ppt_image_101.path = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/17 m 2.png";
ppt_image_101.x = "20%";
ppt_image_101.y = "24%";
ppt_image_101.w ="25%";
ppt_image_101.h ="65%";
ppt_slide_98.addImage(ppt_image_101);
ppt_slide_98_debug.items.push({ image: ppt_image_101 });
ppt_doc_1_debug.slides.push(ppt_slide_98_debug);
const ppt_slide_102 = ppt_doc_1.addSlide();
const ppt_slide_102_debug = { items: [] };
var ppt_p_103 = Object.assign({}, defaultStyle.content);
const ppt_p_103_text = "Tutti a tavola";
ppt_p_103 = Object.assign({},ppt_p_103, (styles["titolo1"] || {}));
ppt_p_103.isTextBox = true;
ppt_slide_102.addText(ppt_p_103_text, ppt_p_103);
ppt_slide_102_debug.items.push({ text: ppt_p_103_text, options: ppt_p_103 });
var ppt_p_104 = Object.assign({}, defaultStyle.content);
const ppt_p_104_text = "18 mesi";
ppt_p_104 = Object.assign({},ppt_p_104, (styles["titolo2"] || {}));
ppt_p_104.isTextBox = true;
ppt_slide_102.addText(ppt_p_104_text, ppt_p_104);
ppt_slide_102_debug.items.push({ text: ppt_p_104_text, options: ppt_p_104 });
const ppt_image_105 = {};
ppt_image_105.path = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/18 mesi.png";
ppt_image_105.x = "20%";
ppt_image_105.y = "24%";
ppt_image_105.w ="25%";
ppt_image_105.h ="65%";
ppt_slide_102.addImage(ppt_image_105);
ppt_slide_102_debug.items.push({ image: ppt_image_105 });
ppt_doc_1_debug.slides.push(ppt_slide_102_debug);
const ppt_slide_106 = ppt_doc_1.addSlide();
const ppt_slide_106_debug = { items: [] };
var ppt_p_107 = Object.assign({}, defaultStyle.content);
const ppt_p_107_text = "Tutti a tavola";
ppt_p_107 = Object.assign({},ppt_p_107, (styles["titolo1"] || {}));
ppt_p_107.isTextBox = true;
ppt_slide_106.addText(ppt_p_107_text, ppt_p_107);
ppt_slide_106_debug.items.push({ text: ppt_p_107_text, options: ppt_p_107 });
var ppt_p_108 = Object.assign({}, defaultStyle.content);
const ppt_p_108_text = "19 mesi";
ppt_p_108 = Object.assign({},ppt_p_108, (styles["titolo2"] || {}));
ppt_p_108.isTextBox = true;
ppt_slide_106.addText(ppt_p_108_text, ppt_p_108);
ppt_slide_106_debug.items.push({ text: ppt_p_108_text, options: ppt_p_108 });
const ppt_image_109 = {};
ppt_image_109.path = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/19 mesi.png";
ppt_image_109.x = "20%";
ppt_image_109.y = "24%";
ppt_image_109.w ="25%";
ppt_image_109.h ="65%";
ppt_slide_106.addImage(ppt_image_109);
ppt_slide_106_debug.items.push({ image: ppt_image_109 });
ppt_doc_1_debug.slides.push(ppt_slide_106_debug);
const ppt_slide_110 = ppt_doc_1.addSlide();
const ppt_slide_110_debug = { items: [] };
var ppt_p_111 = Object.assign({}, defaultStyle.content);
const ppt_p_111_text = "Tutti a tavola";
ppt_p_111 = Object.assign({},ppt_p_111, (styles["titolo1"] || {}));
ppt_p_111.isTextBox = true;
ppt_slide_110.addText(ppt_p_111_text, ppt_p_111);
ppt_slide_110_debug.items.push({ text: ppt_p_111_text, options: ppt_p_111 });
var ppt_p_112 = Object.assign({}, defaultStyle.content);
const ppt_p_112_text = " ";
ppt_p_112 = Object.assign({},ppt_p_112, (styles["titolo2"] || {}));
ppt_p_112.isTextBox = true;
ppt_slide_110.addText(ppt_p_112_text, ppt_p_112);
ppt_slide_110_debug.items.push({ text: ppt_p_112_text, options: ppt_p_112 });
var ppt_p_113 = Object.assign({}, defaultStyle.content);
const ppt_p_113_text = "20 mesi";
ppt_p_113 = Object.assign({},ppt_p_113, (styles[".column-title"] || {}));
ppt_p_113.x = "10%";
ppt_p_113.y = "24%";
ppt_p_113.w ="40%";
ppt_p_113.breakLine = true;
ppt_p_113.isTextBox = true;
ppt_slide_110.addText(ppt_p_113_text, ppt_p_113);
ppt_slide_110_debug.items.push({ text: ppt_p_113_text, options: ppt_p_113 });
var ppt_p_114 = Object.assign({}, defaultStyle.content);
const ppt_p_114_text = "Gli inquinanti alimentari";
ppt_p_114 = Object.assign({},ppt_p_114, (styles[".column-p"] || {}));
ppt_p_114.x = "10%";
ppt_p_114.y = "30%";
ppt_p_114.w ="40%";
ppt_p_114.breakLine = true;
ppt_p_114.isTextBox = true;
ppt_slide_110.addText(ppt_p_114_text, ppt_p_114);
ppt_slide_110_debug.items.push({ text: ppt_p_114_text, options: ppt_p_114 });
var ppt_p_115 = Object.assign({}, defaultStyle.content);
const ppt_p_115_text = "21 mesi";
ppt_p_115 = Object.assign({},ppt_p_115, (styles[".column-title"] || {}));
ppt_p_115.x = "10%";
ppt_p_115.y = "38%";
ppt_p_115.w ="40%";
ppt_p_115.breakLine = true;
ppt_p_115.isTextBox = true;
ppt_slide_110.addText(ppt_p_115_text, ppt_p_115);
ppt_slide_110_debug.items.push({ text: ppt_p_115_text, options: ppt_p_115 });
var ppt_p_116 = Object.assign({}, defaultStyle.content);
const ppt_p_116_text = "I pericoli in cucina";
ppt_p_116 = Object.assign({},ppt_p_116, (styles[".column-p"] || {}));
ppt_p_116.x = "10%";
ppt_p_116.y = "44%";
ppt_p_116.w ="40%";
ppt_p_116.breakLine = true;
ppt_p_116.isTextBox = true;
ppt_slide_110.addText(ppt_p_116_text, ppt_p_116);
ppt_slide_110_debug.items.push({ text: ppt_p_116_text, options: ppt_p_116 });
var ppt_p_117 = Object.assign({}, defaultStyle.content);
const ppt_p_117_text = "22 mesi";
ppt_p_117 = Object.assign({},ppt_p_117, (styles[".column-title"] || {}));
ppt_p_117.x = "10%";
ppt_p_117.y = "52%";
ppt_p_117.w ="40%";
ppt_p_117.breakLine = true;
ppt_p_117.isTextBox = true;
ppt_slide_110.addText(ppt_p_117_text, ppt_p_117);
ppt_slide_110_debug.items.push({ text: ppt_p_117_text, options: ppt_p_117 });
var ppt_p_118 = Object.assign({}, defaultStyle.content);
const ppt_p_118_text = "Il bisogno di fibre";
ppt_p_118 = Object.assign({},ppt_p_118, (styles[".column-p"] || {}));
ppt_p_118.x = "10%";
ppt_p_118.y = "58%";
ppt_p_118.w ="40%";
ppt_p_118.breakLine = true;
ppt_p_118.isTextBox = true;
ppt_slide_110.addText(ppt_p_118_text, ppt_p_118);
ppt_slide_110_debug.items.push({ text: ppt_p_118_text, options: ppt_p_118 });
var ppt_p_119 = Object.assign({}, defaultStyle.content);
const ppt_p_119_text = "2 anni";
ppt_p_119 = Object.assign({},ppt_p_119, (styles[".column-title"] || {}));
ppt_p_119.x = "10%";
ppt_p_119.y = "66%";
ppt_p_119.w ="40%";
ppt_p_119.breakLine = true;
ppt_p_119.isTextBox = true;
ppt_slide_110.addText(ppt_p_119_text, ppt_p_119);
ppt_slide_110_debug.items.push({ text: ppt_p_119_text, options: ppt_p_119 });
var ppt_p_120 = Object.assign({}, defaultStyle.content);
const ppt_p_120_text = "Buone abitudini e strategie per invogliare il tuo bambino a mangiare cibi salutari";
ppt_p_120 = Object.assign({},ppt_p_120, (styles[".column-p"] || {}));
ppt_p_120.x = "10%";
ppt_p_120.y = "72%";
ppt_p_120.w ="40%";
ppt_p_120.breakLine = true;
ppt_p_120.isTextBox = true;
ppt_slide_110.addText(ppt_p_120_text, ppt_p_120);
ppt_slide_110_debug.items.push({ text: ppt_p_120_text, options: ppt_p_120 });
var ppt_p_121 = Object.assign({}, defaultStyle.content);
const ppt_p_121_text = "3 anni e 2 mesi";
ppt_p_121 = Object.assign({},ppt_p_121, (styles[".column-title"] || {}));
ppt_p_121.x = "10%";
ppt_p_121.y = "80%";
ppt_p_121.w ="40%";
ppt_p_121.breakLine = true;
ppt_p_121.isTextBox = true;
ppt_slide_110.addText(ppt_p_121_text, ppt_p_121);
ppt_slide_110_debug.items.push({ text: ppt_p_121_text, options: ppt_p_121 });
var ppt_p_122 = Object.assign({}, defaultStyle.content);
const ppt_p_122_text = "E se non vuole mangiare frutta e verdura?";
ppt_p_122 = Object.assign({},ppt_p_122, (styles[".column-p"] || {}));
ppt_p_122.x = "10%";
ppt_p_122.y = "86%";
ppt_p_122.w ="40%";
ppt_p_122.breakLine = true;
ppt_p_122.isTextBox = true;
ppt_slide_110.addText(ppt_p_122_text, ppt_p_122);
ppt_slide_110_debug.items.push({ text: ppt_p_122_text, options: ppt_p_122 });
const ppt_image_123 = {};
ppt_image_123.path = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/l'orto dei piccoli.jpg";
ppt_image_123.y = "24%";
ppt_image_123.x = "55%";
ppt_image_123.w ="25%";
ppt_image_123.h ="30%";
ppt_slide_110.addImage(ppt_image_123);
ppt_slide_110_debug.items.push({ image: ppt_image_123 });
const ppt_image_124 = {};
ppt_image_124.path = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/mangia i piselli.jpg";
ppt_image_124.y = "59%";
ppt_image_124.x = "55%";
ppt_image_124.w ="25%";
ppt_image_124.h ="30%";
ppt_slide_110.addImage(ppt_image_124);
ppt_slide_110_debug.items.push({ image: ppt_image_124 });
ppt_doc_1_debug.slides.push(ppt_slide_110_debug);
const ppt_slide_125 = ppt_doc_1.addSlide();
const ppt_slide_125_debug = { items: [] };
var ppt_p_126 = Object.assign({}, defaultStyle.content);
const ppt_p_126_text = "Tutti a tavola";
ppt_p_126 = Object.assign({},ppt_p_126, (styles["titolo1"] || {}));
ppt_p_126.isTextBox = true;
ppt_slide_125.addText(ppt_p_126_text, ppt_p_126);
ppt_slide_125_debug.items.push({ text: ppt_p_126_text, options: ppt_p_126 });
var ppt_p_127 = Object.assign({}, defaultStyle.content);
const ppt_p_127_text = " ";
ppt_p_127 = Object.assign({},ppt_p_127, (styles["titolo2"] || {}));
ppt_p_127.isTextBox = true;
ppt_slide_125.addText(ppt_p_127_text, ppt_p_127);
ppt_slide_125_debug.items.push({ text: ppt_p_127_text, options: ppt_p_127 });
var ppt_p_128 = Object.assign({}, defaultStyle.content);
const ppt_p_128_text = "3 anni e 6 mesi";
ppt_p_128 = Object.assign({},ppt_p_128, (styles[".column-title"] || {}));
ppt_p_128.x = "10%";
ppt_p_128.y = "24%";
ppt_p_128.w ="40%";
ppt_p_128.breakLine = true;
ppt_p_128.isTextBox = true;
ppt_slide_125.addText(ppt_p_128_text, ppt_p_128);
ppt_slide_125_debug.items.push({ text: ppt_p_128_text, options: ppt_p_128 });
var ppt_p_129 = Object.assign({}, defaultStyle.content);
const ppt_p_129_text = "Cerca di rendere più sani i tuoi piatti preferiti.\n\n Leggere un libro aiuta a mangiare cibi sani.";
ppt_p_129 = Object.assign({},ppt_p_129, (styles[".column-p"] || {}));
ppt_p_129.x = "10%";
ppt_p_129.y = "30%";
ppt_p_129.w ="40%";
ppt_p_129.breakLine = true;
ppt_p_129.isTextBox = true;
ppt_slide_125.addText(ppt_p_129_text, ppt_p_129);
ppt_slide_125_debug.items.push({ text: ppt_p_129_text, options: ppt_p_129 });
var ppt_p_130 = Object.assign({}, defaultStyle.content);
const ppt_p_130_text = "4 anni e 6 mesi";
ppt_p_130 = Object.assign({},ppt_p_130, (styles[".column-title"] || {}));
ppt_p_130.x = "10%";
ppt_p_130.y = "38%";
ppt_p_130.w ="40%";
ppt_p_130.breakLine = true;
ppt_p_130.isTextBox = true;
ppt_slide_125.addText(ppt_p_130_text, ppt_p_130);
ppt_slide_125_debug.items.push({ text: ppt_p_130_text, options: ppt_p_130 });
var ppt_p_131 = Object.assign({}, defaultStyle.content);
const ppt_p_131_text = "Come fare per essere un modello sano?";
ppt_p_131 = Object.assign({},ppt_p_131, (styles[".column-p"] || {}));
ppt_p_131.x = "10%";
ppt_p_131.y = "44%";
ppt_p_131.w ="40%";
ppt_p_131.breakLine = true;
ppt_p_131.isTextBox = true;
ppt_slide_125.addText(ppt_p_131_text, ppt_p_131);
ppt_slide_125_debug.items.push({ text: ppt_p_131_text, options: ppt_p_131 });
var ppt_p_132 = Object.assign({}, defaultStyle.content);
const ppt_p_132_text = "5 anni e 3 mesi";
ppt_p_132 = Object.assign({},ppt_p_132, (styles[".column-title"] || {}));
ppt_p_132.x = "10%";
ppt_p_132.y = "52%";
ppt_p_132.w ="40%";
ppt_p_132.breakLine = true;
ppt_p_132.isTextBox = true;
ppt_slide_125.addText(ppt_p_132_text, ppt_p_132);
ppt_slide_125_debug.items.push({ text: ppt_p_132_text, options: ppt_p_132 });
var ppt_p_133 = Object.assign({}, defaultStyle.content);
const ppt_p_133_text = "Fra i 5 e i 6 anni sarà molto utile un Bilancio di salute dal tuo pediatra";
ppt_p_133 = Object.assign({},ppt_p_133, (styles[".column-p"] || {}));
ppt_p_133.x = "10%";
ppt_p_133.y = "58%";
ppt_p_133.w ="40%";
ppt_p_133.breakLine = true;
ppt_p_133.isTextBox = true;
ppt_slide_125.addText(ppt_p_133_text, ppt_p_133);
ppt_slide_125_debug.items.push({ text: ppt_p_133_text, options: ppt_p_133 });
const ppt_image_134 = {};
ppt_image_134.path = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/musi piatti.jpg";
ppt_image_134.y = "24%";
ppt_image_134.x = "55%";
ppt_image_134.w ="25%";
ppt_image_134.h ="30%";
ppt_slide_125.addImage(ppt_image_134);
ppt_slide_125_debug.items.push({ image: ppt_image_134 });
const ppt_image_135 = {};
ppt_image_135.path = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/è ora di mangiare sano.jpg";
ppt_image_135.y = "59%";
ppt_image_135.x = "55%";
ppt_image_135.w ="25%";
ppt_image_135.h ="30%";
ppt_slide_125.addImage(ppt_image_135);
ppt_slide_125_debug.items.push({ image: ppt_image_135 });
const ppt_image_136 = {};
ppt_image_136.path = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/bminforma.png";
ppt_image_136.y = "94%";
ppt_image_136.x = "55%";
ppt_image_136.w ="25%";
ppt_image_136.h ="30%";
ppt_slide_125.addImage(ppt_image_136);
ppt_slide_125_debug.items.push({ image: ppt_image_136 });
ppt_doc_1_debug.slides.push(ppt_slide_125_debug);
const ppt_slide_137 = ppt_doc_1.addSlide();
const ppt_slide_137_debug = { items: [] };
var ppt_p_138 = Object.assign({}, defaultStyle.content);
const ppt_p_138_text = "Tutti a tavola";
ppt_p_138 = Object.assign({},ppt_p_138, (styles["titolo1"] || {}));
ppt_p_138.isTextBox = true;
ppt_slide_137.addText(ppt_p_138_text, ppt_p_138);
ppt_slide_137_debug.items.push({ text: ppt_p_138_text, options: ppt_p_138 });
var ppt_p_139 = Object.assign({}, defaultStyle.content);
const ppt_p_139_text = "5 anni e 9 mesi/1";
ppt_p_139 = Object.assign({},ppt_p_139, (styles["titolo2"] || {}));
ppt_p_139.isTextBox = true;
ppt_slide_137.addText(ppt_p_139_text, ppt_p_139);
ppt_slide_137_debug.items.push({ text: ppt_p_139_text, options: ppt_p_139 });
const ppt_image_140 = {};
ppt_image_140.path = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/5a 9 m.png";
ppt_image_140.x = "20%";
ppt_image_140.y = "24%";
ppt_image_140.w ="25%";
ppt_image_140.h ="65%";
ppt_slide_137.addImage(ppt_image_140);
ppt_slide_137_debug.items.push({ image: ppt_image_140 });
ppt_doc_1_debug.slides.push(ppt_slide_137_debug);
const ppt_slide_141 = ppt_doc_1.addSlide();
const ppt_slide_141_debug = { items: [] };
var ppt_p_142 = Object.assign({}, defaultStyle.content);
const ppt_p_142_text = "Tutti a tavola";
ppt_p_142 = Object.assign({},ppt_p_142, (styles["titolo1"] || {}));
ppt_p_142.isTextBox = true;
ppt_slide_141.addText(ppt_p_142_text, ppt_p_142);
ppt_slide_141_debug.items.push({ text: ppt_p_142_text, options: ppt_p_142 });
var ppt_p_143 = Object.assign({}, defaultStyle.content);
const ppt_p_143_text = "5 anni e 9 mesi/2";
ppt_p_143 = Object.assign({},ppt_p_143, (styles["titolo2"] || {}));
ppt_p_143.isTextBox = true;
ppt_slide_141.addText(ppt_p_143_text, ppt_p_143);
ppt_slide_141_debug.items.push({ text: ppt_p_143_text, options: ppt_p_143 });
const ppt_image_144 = {};
ppt_image_144.path = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/5a 9m 2.png";
ppt_image_144.x = "20%";
ppt_image_144.y = "24%";
ppt_image_144.w ="25%";
ppt_image_144.h ="65%";
ppt_slide_141.addImage(ppt_image_144);
ppt_slide_141_debug.items.push({ image: ppt_image_144 });
ppt_doc_1_debug.slides.push(ppt_slide_141_debug);
const ppt_slide_145 = ppt_doc_1.addSlide();
const ppt_slide_145_debug = { items: [] };
var ppt_p_146 = Object.assign({}, defaultStyle.content);
const ppt_p_146_text = "Tutti a tavola";
ppt_p_146 = Object.assign({},ppt_p_146, (styles["titolo1"] || {}));
ppt_p_146.isTextBox = true;
ppt_slide_145.addText(ppt_p_146_text, ppt_p_146);
ppt_slide_145_debug.items.push({ text: ppt_p_146_text, options: ppt_p_146 });
var ppt_p_147 = Object.assign({}, defaultStyle.content);
const ppt_p_147_text = "6 anni";
ppt_p_147 = Object.assign({},ppt_p_147, (styles["titolo2"] || {}));
ppt_p_147.isTextBox = true;
ppt_slide_145.addText(ppt_p_147_text, ppt_p_147);
ppt_slide_145_debug.items.push({ text: ppt_p_147_text, options: ppt_p_147 });
var ppt_p_148 = Object.assign({}, defaultStyle.content);
const ppt_p_148_text = "";
ppt_p_148 = Object.assign({},ppt_p_148, (styles[".column-title"] || {}));
ppt_p_148.x = "10%";
ppt_p_148.y = "24%";
ppt_p_148.w ="40%";
ppt_p_148.breakLine = true;
ppt_p_148.isTextBox = true;
ppt_slide_145.addText(ppt_p_148_text, ppt_p_148);
ppt_slide_145_debug.items.push({ text: ppt_p_148_text, options: ppt_p_148 });
var ppt_p_149 = Object.assign({}, defaultStyle.content);
const ppt_p_149_text = "\n\n\n\n\n\n\n\nColtiva un piccolo orto domestico";
ppt_p_149 = Object.assign({},ppt_p_149, (styles[".column-p"] || {}));
ppt_p_149.x = "10%";
ppt_p_149.y = "30%";
ppt_p_149.w ="40%";
ppt_p_149.breakLine = true;
ppt_p_149.isTextBox = true;
ppt_slide_145.addText(ppt_p_149_text, ppt_p_149);
ppt_slide_145_debug.items.push({ text: ppt_p_149_text, options: ppt_p_149 });
const ppt_image_150 = {};
ppt_image_150.path = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/l'orto dei bimbi.jpg";
ppt_image_150.y = "24%";
ppt_image_150.x = "55%";
ppt_image_150.w ="25%";
ppt_image_150.h ="30%";
ppt_slide_145.addImage(ppt_image_150);
ppt_slide_145_debug.items.push({ image: ppt_image_150 });
const ppt_image_151 = {};
ppt_image_151.path = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/bimbi orticoltori.jpg";
ppt_image_151.y = "59%";
ppt_image_151.x = "55%";
ppt_image_151.w ="25%";
ppt_image_151.h ="30%";
ppt_slide_145.addImage(ppt_image_151);
ppt_slide_145_debug.items.push({ image: ppt_image_151 });
ppt_doc_1_debug.slides.push(ppt_slide_145_debug);
const ppt_slide_152 = ppt_doc_1.addSlide();
const ppt_slide_152_debug = { items: [] };
var ppt_p_153 = Object.assign({}, defaultStyle.content);
const ppt_p_153_text = "Tutti a tavola";
ppt_p_153 = Object.assign({},ppt_p_153, (styles["titolo1"] || {}));
ppt_p_153.isTextBox = true;
ppt_slide_152.addText(ppt_p_153_text, ppt_p_153);
ppt_slide_152_debug.items.push({ text: ppt_p_153_text, options: ppt_p_153 });
var ppt_p_154 = Object.assign({}, defaultStyle.content);
const ppt_p_154_text = " ";
ppt_p_154 = Object.assign({},ppt_p_154, (styles["titolo2"] || {}));
ppt_p_154.isTextBox = true;
ppt_slide_152.addText(ppt_p_154_text, ppt_p_154);
ppt_slide_152_debug.items.push({ text: ppt_p_154_text, options: ppt_p_154 });
var ppt_p_155 = Object.assign({}, defaultStyle.content);
const ppt_p_155_text = "6 anni";
ppt_p_155 = Object.assign({},ppt_p_155, (styles[".column-title"] || {}));
ppt_p_155.x = "10%";
ppt_p_155.y = "24%";
ppt_p_155.w ="40%";
ppt_p_155.breakLine = true;
ppt_p_155.isTextBox = true;
ppt_slide_152.addText(ppt_p_155_text, ppt_p_155);
ppt_slide_152_debug.items.push({ text: ppt_p_155_text, options: ppt_p_155 });
var ppt_p_156 = Object.assign({}, defaultStyle.content);
const ppt_p_156_text = "\n\n\n\nDiventa un critico gastronomico...\n\n\n\n\n\n\n\n\n\n I momenti speciali a tavola uniscono la famiglia";
ppt_p_156 = Object.assign({},ppt_p_156, (styles[".column-p"] || {}));
ppt_p_156.x = "10%";
ppt_p_156.y = "30%";
ppt_p_156.w ="40%";
ppt_p_156.breakLine = true;
ppt_p_156.isTextBox = true;
ppt_slide_152.addText(ppt_p_156_text, ppt_p_156);
ppt_slide_152_debug.items.push({ text: ppt_p_156_text, options: ppt_p_156 });
const ppt_image_157 = {};
ppt_image_157.path = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/3 cuochi.jpg";
ppt_image_157.y = "24%";
ppt_image_157.x = "55%";
ppt_image_157.w ="25%";
ppt_image_157.h ="30%";
ppt_slide_152.addImage(ppt_image_157);
ppt_slide_152_debug.items.push({ image: ppt_image_157 });
const ppt_image_158 = {};
ppt_image_158.path = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/momenti speciali a tavola.jpg";
ppt_image_158.y = "59%";
ppt_image_158.x = "55%";
ppt_image_158.w ="25%";
ppt_image_158.h ="30%";
ppt_slide_152.addImage(ppt_image_158);
ppt_slide_152_debug.items.push({ image: ppt_image_158 });
ppt_doc_1_debug.slides.push(ppt_slide_152_debug);
const ppt_slide_159 = ppt_doc_1.addSlide();
const ppt_slide_159_debug = { items: [] };
var ppt_p_160 = Object.assign({}, defaultStyle.content);
const ppt_p_160_text = "NpL e NpM";
ppt_p_160 = Object.assign({},ppt_p_160, (styles["titolo1"] || {}));
ppt_p_160.isTextBox = true;
ppt_slide_159.addText(ppt_p_160_text, ppt_p_160);
ppt_slide_159_debug.items.push({ text: ppt_p_160_text, options: ppt_p_160 });
var ppt_p_161 = Object.assign({}, defaultStyle.content);
const ppt_p_161_text = " ";
ppt_p_161 = Object.assign({},ppt_p_161, (styles["titolo2"] || {}));
ppt_p_161.isTextBox = true;
ppt_slide_159.addText(ppt_p_161_text, ppt_p_161);
ppt_slide_159_debug.items.push({ text: ppt_p_161_text, options: ppt_p_161 });
var ppt_p_162 = Object.assign({}, defaultStyle.content);
const ppt_p_162_text = "Proposte di libri e ascolti musicali per le varie età";
ppt_p_162 = Object.assign({},ppt_p_162, (styles["para1"] || {}));
ppt_p_162.x = "10%";
ppt_p_162.y = "48%";
ppt_p_162.w ="80%";
ppt_p_162.isTextBox = true;
ppt_slide_159.addText(ppt_p_162_text, ppt_p_162);
ppt_slide_159_debug.items.push({ text: ppt_p_162_text, options: ppt_p_162 });
var ppt_p_163 = Object.assign({}, defaultStyle.content);
const ppt_p_163_text = "Consigli";
ppt_p_163 = Object.assign({},ppt_p_163, (styles["para1"] || {}));
ppt_p_163.x = "10%";
ppt_p_163.y = "58%";
ppt_p_163.w ="80%";
ppt_p_163.isTextBox = true;
ppt_slide_159.addText(ppt_p_163_text, ppt_p_163);
ppt_slide_159_debug.items.push({ text: ppt_p_163_text, options: ppt_p_163 });
var ppt_p_164 = Object.assign({}, defaultStyle.content);
const ppt_p_164_text = "Tanti libri di qualità per ogni età";
ppt_p_164 = Object.assign({},ppt_p_164, (styles["para1"] || {}));
const ppt_bulletObj_165 = {};
ppt_bulletObj_165.indent = 6;
ppt_bulletObj_165.code = "2B24";
ppt_p_164.bullet = ppt_bulletObj_165;
ppt_p_164.x = "10%";
ppt_p_164.y = "68%";
ppt_p_164.w ="80%";
ppt_p_164.isTextBox = true;
ppt_slide_159.addText(ppt_p_164_text, ppt_p_164);
ppt_slide_159_debug.items.push({ text: ppt_p_164_text, options: ppt_p_164 });
var ppt_p_166 = Object.assign({}, defaultStyle.content);
const ppt_p_166_text = "Le modalità di lettura";
ppt_p_166 = Object.assign({},ppt_p_166, (styles["para1"] || {}));
const ppt_bulletObj_167 = {};
ppt_bulletObj_167.indent = 6;
ppt_bulletObj_167.code = "2B24";
ppt_p_166.bullet = ppt_bulletObj_167;
ppt_p_166.x = "10%";
ppt_p_166.y = "78%";
ppt_p_166.w ="80%";
ppt_p_166.isTextBox = true;
ppt_slide_159.addText(ppt_p_166_text, ppt_p_166);
ppt_slide_159_debug.items.push({ text: ppt_p_166_text, options: ppt_p_166 });
var ppt_p_168 = Object.assign({}, defaultStyle.content);
const ppt_p_168_text = "Frequentare la biblioteca";
ppt_p_168 = Object.assign({},ppt_p_168, (styles["para1"] || {}));
const ppt_bulletObj_169 = {};
ppt_bulletObj_169.indent = 6;
ppt_bulletObj_169.code = "2B24";
ppt_p_168.bullet = ppt_bulletObj_169;
ppt_p_168.x = "10%";
ppt_p_168.y = "88%";
ppt_p_168.w ="80%";
ppt_p_168.isTextBox = true;
ppt_slide_159.addText(ppt_p_168_text, ppt_p_168);
ppt_slide_159_debug.items.push({ text: ppt_p_168_text, options: ppt_p_168 });
var ppt_p_170 = Object.assign({}, defaultStyle.content);
const ppt_p_170_text = "Frequentare le librerie";
ppt_p_170 = Object.assign({},ppt_p_170, (styles["para1"] || {}));
const ppt_bulletObj_171 = {};
ppt_bulletObj_171.indent = 6;
ppt_bulletObj_171.code = "2B24";
ppt_p_170.bullet = ppt_bulletObj_171;
ppt_p_170.x = "10%";
ppt_p_170.y = "98%";
ppt_p_170.w ="80%";
ppt_p_170.isTextBox = true;
ppt_slide_159.addText(ppt_p_170_text, ppt_p_170);
ppt_slide_159_debug.items.push({ text: ppt_p_170_text, options: ppt_p_170 });
ppt_doc_1_debug.slides.push(ppt_slide_159_debug);
const ppt_slide_172 = ppt_doc_1.addSlide();
const ppt_slide_172_debug = { items: [] };
var ppt_p_173 = Object.assign({}, defaultStyle.content);
const ppt_p_173_text = "NpL e NpM";
ppt_p_173 = Object.assign({},ppt_p_173, (styles["titolo1"] || {}));
ppt_p_173.isTextBox = true;
ppt_slide_172.addText(ppt_p_173_text, ppt_p_173);
ppt_slide_172_debug.items.push({ text: ppt_p_173_text, options: ppt_p_173 });
var ppt_p_174 = Object.assign({}, defaultStyle.content);
const ppt_p_174_text = "3 anni e 6 mesi, Papà";
ppt_p_174 = Object.assign({},ppt_p_174, (styles["titolo2"] || {}));
ppt_p_174.isTextBox = true;
ppt_slide_172.addText(ppt_p_174_text, ppt_p_174);
ppt_slide_172_debug.items.push({ text: ppt_p_174_text, options: ppt_p_174 });
const ppt_image_175 = {};
ppt_image_175.path = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/NpL 2.png";
ppt_image_175.x = "20%";
ppt_image_175.y = "24%";
ppt_image_175.w ="25%";
ppt_image_175.h ="65%";
ppt_slide_172.addImage(ppt_image_175);
ppt_slide_172_debug.items.push({ image: ppt_image_175 });
ppt_doc_1_debug.slides.push(ppt_slide_172_debug);
const ppt_slide_176 = ppt_doc_1.addSlide();
const ppt_slide_176_debug = { items: [] };
var ppt_p_177 = Object.assign({}, defaultStyle.content);
const ppt_p_177_text = "NpL e NpM";
ppt_p_177 = Object.assign({},ppt_p_177, (styles["titolo1"] || {}));
ppt_p_177.isTextBox = true;
ppt_slide_176.addText(ppt_p_177_text, ppt_p_177);
ppt_slide_176_debug.items.push({ text: ppt_p_177_text, options: ppt_p_177 });
var ppt_p_178 = Object.assign({}, defaultStyle.content);
const ppt_p_178_text = "4 anni, Dialogico";
ppt_p_178 = Object.assign({},ppt_p_178, (styles["titolo2"] || {}));
ppt_p_178.isTextBox = true;
ppt_slide_176.addText(ppt_p_178_text, ppt_p_178);
ppt_slide_176_debug.items.push({ text: ppt_p_178_text, options: ppt_p_178 });
const ppt_image_179 = {};
ppt_image_179.path = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/NpL 3.png";
ppt_image_179.x = "20%";
ppt_image_179.y = "24%";
ppt_image_179.w ="25%";
ppt_image_179.h ="65%";
ppt_slide_176.addImage(ppt_image_179);
ppt_slide_176_debug.items.push({ image: ppt_image_179 });
ppt_doc_1_debug.slides.push(ppt_slide_176_debug);
const ppt_slide_180 = ppt_doc_1.addSlide();
const ppt_slide_180_debug = { items: [] };
var ppt_p_181 = Object.assign({}, defaultStyle.content);
const ppt_p_181_text = "La App BeBa, un lavoro da implementare";
ppt_p_181 = Object.assign({},ppt_p_181, (styles["titolo1"] || {}));
ppt_p_181.isTextBox = true;
ppt_slide_180.addText(ppt_p_181_text, ppt_p_181);
ppt_slide_180_debug.items.push({ text: ppt_p_181_text, options: ppt_p_181 });
var ppt_p_182 = Object.assign({}, defaultStyle.content);
const ppt_p_182_text = " ";
ppt_p_182 = Object.assign({},ppt_p_182, (styles["titolo2"] || {}));
ppt_p_182.isTextBox = true;
ppt_slide_180.addText(ppt_p_182_text, ppt_p_182);
ppt_slide_180_debug.items.push({ text: ppt_p_182_text, options: ppt_p_182 });
var ppt_p_183 = Object.assign({}, defaultStyle.content);
const ppt_p_183_text = " ";
ppt_p_183 = Object.assign({},ppt_p_183, (styles[".column-title"] || {}));
ppt_p_183.x = "10%";
ppt_p_183.y = "24%";
ppt_p_183.w ="40%";
ppt_p_183.breakLine = true;
ppt_p_183.isTextBox = true;
ppt_slide_180.addText(ppt_p_183_text, ppt_p_183);
ppt_slide_180_debug.items.push({ text: ppt_p_183_text, options: ppt_p_183 });
var ppt_p_184 = Object.assign({}, defaultStyle.content);
const ppt_p_184_text = "Con i feedback dei genitori";
ppt_p_184 = Object.assign({},ppt_p_184, (styles[".column-p-big"] || {}));
ppt_p_184.x = "10%";
ppt_p_184.y = "30%";
ppt_p_184.w ="40%";
ppt_p_184.breakLine = true;
ppt_p_184.isTextBox = true;
ppt_slide_180.addText(ppt_p_184_text, ppt_p_184);
ppt_slide_180_debug.items.push({ text: ppt_p_184_text, options: ppt_p_184 });
var ppt_p_185 = Object.assign({}, defaultStyle.content);
const ppt_p_185_text = " ";
ppt_p_185 = Object.assign({},ppt_p_185, (styles[".column-title"] || {}));
ppt_p_185.x = "10%";
ppt_p_185.y = "38%";
ppt_p_185.w ="40%";
ppt_p_185.breakLine = true;
ppt_p_185.isTextBox = true;
ppt_slide_180.addText(ppt_p_185_text, ppt_p_185);
ppt_slide_180_debug.items.push({ text: ppt_p_185_text, options: ppt_p_185 });
var ppt_p_186 = Object.assign({}, defaultStyle.content);
const ppt_p_186_text = "Con i feedback dei pediatri";
ppt_p_186 = Object.assign({},ppt_p_186, (styles[".column-p-big"] || {}));
ppt_p_186.x = "10%";
ppt_p_186.y = "44%";
ppt_p_186.w ="40%";
ppt_p_186.breakLine = true;
ppt_p_186.isTextBox = true;
ppt_slide_180.addText(ppt_p_186_text, ppt_p_186);
ppt_slide_180_debug.items.push({ text: ppt_p_186_text, options: ppt_p_186 });
const ppt_image_187 = {};
ppt_image_187.path = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/work in progress.png";
ppt_image_187.y = "24%";
ppt_image_187.x = "55%";
ppt_image_187.w ="25%";
ppt_image_187.h ="30%";
ppt_slide_180.addImage(ppt_image_187);
ppt_slide_180_debug.items.push({ image: ppt_image_187 });
ppt_doc_1_debug.slides.push(ppt_slide_180_debug);
const ppt_slide_188 = ppt_doc_1.addSlide();
const ppt_slide_188_debug = { items: [] };
var ppt_p_189 = Object.assign({}, defaultStyle.content);
const ppt_p_189_text = "Grazie";
ppt_p_189 = Object.assign({},ppt_p_189, (styles[".thanks-title"] || {}));
ppt_p_189.y = "30%";
ppt_p_189.isTextBox = true;
ppt_slide_188.addText(ppt_p_189_text, ppt_p_189);
ppt_slide_188_debug.items.push({ text: ppt_p_189_text, options: ppt_p_189 });
var ppt_p_190 = Object.assign({}, defaultStyle.content);
const ppt_p_190_text = "per l'attenzione";
ppt_p_190 = Object.assign({},ppt_p_190, (styles[".thanks-subtitle"] || {}));
ppt_p_190.y = "50%";
ppt_p_190.isTextBox = true;
ppt_slide_188.addText(ppt_p_190_text, ppt_p_190);
ppt_slide_188_debug.items.push({ text: ppt_p_190_text, options: ppt_p_190 });
ppt_doc_1_debug.slides.push(ppt_slide_188_debug);

// Dump for test
    fs.writeFileSync(__dirname + "/Davoli_Cosie17marzo2021.ppt.json", JSON.stringify(ppt_doc_1_debug, null, "	"));

// Make Ppt

var now = new Date();

ppt_doc_1.writeFile(
    __dirname + "/Davoli_Cosie17marzo2021.ppt"
).then(fileName => {
    console.log(`created file: ${fileName}`);
    console.log("DONE written", new Date() - now)
});
