const fs = require("fs");
const pdfmake = require("pdfmake");

const pdf_doc_1 = { content: [], styles: {} };
const pdf_styleDef_2 = {};
pdf_styleDef_2.fontSize = 48;
pdf_styleDef_2.bold = true;
pdf_styleDef_2.italics = true;
pdf_styleDef_2.color = "red";
pdf_styleDef_2.alignment = "right";
pdf_doc_1.styles["titolo1"] = pdf_styleDef_2;
const pdf_styleDef_3 = {};
pdf_styleDef_3.fontSize = 36;
pdf_styleDef_3.bold = true;
pdf_styleDef_3.italics = true;
pdf_styleDef_3.color = "#e02424";
pdf_styleDef_3.alignment = "left";
pdf_doc_1.styles["titolo2"] = pdf_styleDef_3;
const pdf_styleDef_4 = {};
pdf_styleDef_4.fontSize = 24;
pdf_styleDef_4.alignment = "left";
pdf_doc_1.styles["para1"] = pdf_styleDef_4;
const pdf_sect_5 = { content: [], styles: {} };
const pdf_p_6 = {};
pdf_p_6.text = [];
pdf_p_6.text.push("Tutti a tavola");
pdf_p_6.style = "titolo1";
pdf_sect_5.content.push(pdf_p_6);
const pdf_p_7 = {};
pdf_p_7.text = [];
pdf_p_7.text.push("0");
pdf_p_7.style = "titolo2";
pdf_sect_5.content.push(pdf_p_7);
const pdf_p_8 = {};
pdf_p_8.text = [];
pdf_p_8.text.push("Header");
pdf_sect_5.content.push(pdf_p_8);
const pdf_MainObject = { sections : [] };
pdf_sect_5.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_5);
const pdf_sect_9 = { content: [], styles: {} };
const pdf_p_10 = {};
pdf_p_10.text = [];
pdf_p_10.text.push("Tutti a tavola");
pdf_p_10.style = "titolo1";
pdf_sect_9.content.push(pdf_p_10);
const pdf_p_11 = {};
pdf_p_11.text = [];
pdf_p_11.text.push("Le App a supporto di genitori e caregiver");
pdf_p_11.style = "titolo2";
pdf_sect_9.content.push(pdf_p_11);
const pdf_ul_12 = {};
pdf_ul_12.ul = [];
const pdf_txt_13 = {};
pdf_txt_13.text = "Contenuti basati sulle evidenze";
pdf_txt_13.style = "para1";
pdf_ul_12["ul"].push(pdf_txt_13);
const pdf_txt_14 = {};
pdf_txt_14.text = "Informazioni coerenti con le linee guida";
pdf_txt_14.style = "para1";
pdf_ul_12["ul"].push(pdf_txt_14);
const pdf_txt_15 = {};
pdf_txt_15.text = "Sviluppate con il supporto di professionisti sanitari";
pdf_txt_15.style = "para1";
pdf_ul_12["ul"].push(pdf_txt_15);
const pdf_txt_16 = {};
pdf_txt_16.text = "Con finanziamento adeguato (del Servizio Sanitario)";
pdf_txt_16.style = "para1";
pdf_ul_12["ul"].push(pdf_txt_16);
pdf_sect_9["content"].push(pdf_ul_12);
const pdf_p_17 = {};
pdf_p_17.text = [];
pdf_p_17.text.push("Garantiscono che ai genitori vengano fornite risorse credibili e affidabili.");
pdf_p_17.style = "para1";
pdf_sect_9.content.push(pdf_p_17);
pdf_sect_9.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_9);
const pdf_sect_18 = { content: [], styles: {} };
const pdf_p_19 = {};
pdf_p_19.text = [];
pdf_p_19.text.push("Tutti a tavola");
pdf_p_19.style = "titolo1";
pdf_sect_18.content.push(pdf_p_19);
const pdf_p_20 = {};
pdf_p_20.text = [];
pdf_p_20.text.push("Una App aiuta i genitori?");
pdf_p_20.style = "titolo2";
pdf_sect_18.content.push(pdf_p_20);
const pdf_p_21 = {};
pdf_p_21.text = [];
pdf_p_21.text.push("Un programma eHealth (sanità digitale) di prevenzione dell'obesità infantile incentrato sui genitori può fornire supporto per migliorare l'alimentazione del bambino e l'autoefficacia parentale.");
pdf_p_21.style = "para1";
pdf_sect_18.content.push(pdf_p_21);
const pdf_p_22 = {};
pdf_p_22.text = [];
pdf_p_22.text.push("Migliora l'alimentazione anche dei genitori.");
pdf_p_22.style = "para1";
pdf_sect_18.content.push(pdf_p_22);
const pdf_p_23 = {};
pdf_p_23.text = [];
pdf_p_23.text.push("Dal 91,2%  al 97,1% dei genitori che hanno utilizzato l'app può valutare più correttamente i parametri di crescita del proprio bambino.");
pdf_p_23.style = "para1";
pdf_sect_18.content.push(pdf_p_23);
pdf_sect_18.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_18);
const pdf_sect_24 = { content: [], styles: {} };
const pdf_p_25 = {};
pdf_p_25.text = [];
pdf_p_25.text.push("Tutti a tavola");
pdf_p_25.style = "titolo1";
pdf_sect_24.content.push(pdf_p_25);
const pdf_p_26 = {};
pdf_p_26.text = [];
pdf_p_26.text.push("La App BeBa");
pdf_p_26.style = "titolo2";
pdf_sect_24.content.push(pdf_p_26);
const pdf_p_27 = {};
pdf_p_27.text = [];
pdf_p_27.text.push("La App si propone l'obiettivo di essere uno stimolo per le famiglie per contrastare l'obesità infantile.");
pdf_p_27.style = "para1";
pdf_sect_24.content.push(pdf_p_27);
const pdf_p_28 = {};
pdf_p_28.text = [];
pdf_p_28.text.push("La guida Tutti a tavola ha la responsabilità di fornire indicazioni basate sulle evidenze disponibili, ma anche la necessità di essere condivisa dai pediatri in modo che i contenuti vengano supportati dall'invito a scaricarla e usarla quale accompagnamento alle parole del Pediatra.");
pdf_p_28.style = "para1";
pdf_sect_24.content.push(pdf_p_28);
const pdf_p_29 = {};
pdf_p_29.text = [];
pdf_p_29.text.push("Sarebbe davvero sgradevole che quello che trovano scritto i genitori contrastasse con i suggerimenti del pediatra.");
pdf_p_29.style = "para1";
pdf_sect_24.content.push(pdf_p_29);
const pdf_p_30 = {};
pdf_p_30.text = [];
pdf_p_30.text.push("Non vi è nulla di prescrittivo, ma quando parliamo di allattamento  e di alimentazione complementare i tempi e le modalità, se non condivise devono offrire al genitore una spiegazione soddisfacente che non si ponga in contrasto con i contenuti delle guide.");
pdf_p_30.style = "para1";
pdf_sect_24.content.push(pdf_p_30);
pdf_sect_24.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_24);
const pdf_sect_31 = { content: [], styles: {} };
const pdf_p_32 = {};
pdf_p_32.text = [];
pdf_p_32.text.push("Tutti a tavola");
pdf_p_32.style = "titolo1";
pdf_sect_31.content.push(pdf_p_32);
const pdf_p_33 = {};
pdf_p_33.text = [];
pdf_p_33.text.push("nascita");
pdf_p_33.style = "titolo2";
pdf_sect_31.content.push(pdf_p_33);
const pdf_image_34 = {};
pdf_image_34.image = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/nascita.png";
pdf_image_34.width = 300;
pdf_image_34.height = 600;
pdf_sect_31["content"].push(pdf_image_34);
pdf_sect_31.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_31);
const pdf_sect_35 = { content: [], styles: {} };
const pdf_p_36 = {};
pdf_p_36.text = [];
pdf_p_36.text.push("Tutti a tavola");
pdf_p_36.style = "titolo1";
pdf_sect_35.content.push(pdf_p_36);
const pdf_p_37 = {};
pdf_p_37.text = [];
pdf_p_37.text.push("15 giorni");
pdf_p_37.style = "titolo2";
pdf_sect_35.content.push(pdf_p_37);
const pdf_image_38 = {};
pdf_image_38.image = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/15 giorni.png";
pdf_image_38.width = 300;
pdf_image_38.height = 600;
pdf_sect_35["content"].push(pdf_image_38);
pdf_sect_35.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_35);
const pdf_sect_39 = { content: [], styles: {} };
const pdf_p_40 = {};
pdf_p_40.text = [];
pdf_p_40.text.push("Tutti a tavola");
pdf_p_40.style = "titolo1";
pdf_sect_39.content.push(pdf_p_40);
const pdf_p_41 = {};
pdf_p_41.text = [];
pdf_p_41.text.push("1 mese");
pdf_p_41.style = "titolo2";
pdf_sect_39.content.push(pdf_p_41);
const pdf_image_42 = {};
pdf_image_42.image = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/1 mese.png";
pdf_image_42.width = 300;
pdf_image_42.height = 600;
pdf_sect_39["content"].push(pdf_image_42);
pdf_sect_39.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_39);
const pdf_sect_43 = { content: [], styles: {} };
const pdf_p_44 = {};
pdf_p_44.text = [];
pdf_p_44.text.push("Tutti a tavola");
pdf_p_44.style = "titolo1";
pdf_sect_43.content.push(pdf_p_44);
const pdf_p_45 = {};
pdf_p_45.text = [];
pdf_p_45.text.push("5 mesi");
pdf_p_45.style = "titolo2";
pdf_sect_43.content.push(pdf_p_45);
const pdf_image_46 = {};
pdf_image_46.image = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/5 mesi.png";
pdf_image_46.width = 300;
pdf_image_46.height = 600;
pdf_sect_43["content"].push(pdf_image_46);
pdf_sect_43.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_43);
const pdf_sect_47 = { content: [], styles: {} };
const pdf_p_48 = {};
pdf_p_48.text = [];
pdf_p_48.text.push("Tutti a tavola");
pdf_p_48.style = "titolo1";
pdf_sect_47.content.push(pdf_p_48);
const pdf_p_49 = {};
pdf_p_49.text = [];
pdf_p_49.text.push("6 mesi");
pdf_p_49.style = "titolo2";
pdf_sect_47.content.push(pdf_p_49);
const pdf_image_50 = {};
pdf_image_50.image = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/6 mesi.png";
pdf_image_50.width = 300;
pdf_image_50.height = 600;
pdf_sect_47["content"].push(pdf_image_50);
pdf_sect_47.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_47);
const pdf_sect_51 = { content: [], styles: {} };
const pdf_p_52 = {};
pdf_p_52.text = [];
pdf_p_52.text.push("Tutti a tavola");
pdf_p_52.style = "titolo1";
pdf_sect_51.content.push(pdf_p_52);
const pdf_p_53 = {};
pdf_p_53.text = [];
pdf_p_53.text.push("9 mesi/1");
pdf_p_53.style = "titolo2";
pdf_sect_51.content.push(pdf_p_53);
const pdf_image_54 = {};
pdf_image_54.image = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/9 mesi 1.png";
pdf_image_54.width = 300;
pdf_image_54.height = 600;
pdf_sect_51["content"].push(pdf_image_54);
pdf_sect_51.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_51);
const pdf_sect_55 = { content: [], styles: {} };
const pdf_p_56 = {};
pdf_p_56.text = [];
pdf_p_56.text.push("Tutti a tavola");
pdf_p_56.style = "titolo1";
pdf_sect_55.content.push(pdf_p_56);
const pdf_p_57 = {};
pdf_p_57.text = [];
pdf_p_57.text.push("9 mesi/2");
pdf_p_57.style = "titolo2";
pdf_sect_55.content.push(pdf_p_57);
const pdf_image_58 = {};
pdf_image_58.image = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/9 mesi 2.png";
pdf_image_58.width = 300;
pdf_image_58.height = 600;
pdf_sect_55["content"].push(pdf_image_58);
pdf_sect_55.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_55);
const pdf_sect_59 = { content: [], styles: {} };
const pdf_p_60 = {};
pdf_p_60.text = [];
pdf_p_60.text.push("Tutti a tavola");
pdf_p_60.style = "titolo1";
pdf_sect_59.content.push(pdf_p_60);
const pdf_p_61 = {};
pdf_p_61.text = [];
pdf_p_61.text.push("1 anno");
pdf_p_61.style = "titolo2";
pdf_sect_59.content.push(pdf_p_61);
const pdf_image_62 = {};
pdf_image_62.image = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/1 anno.png";
pdf_image_62.width = 300;
pdf_image_62.height = 600;
pdf_sect_59["content"].push(pdf_image_62);
pdf_sect_59.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_59);
const pdf_sect_63 = { content: [], styles: {} };
const pdf_p_64 = {};
pdf_p_64.text = [];
pdf_p_64.text.push("Tutti a tavola");
pdf_p_64.style = "titolo1";
pdf_sect_63.content.push(pdf_p_64);
const pdf_p_65 = {};
pdf_p_65.text = [];
pdf_p_65.text.push("14 mesi");
pdf_p_65.style = "titolo2";
pdf_sect_63.content.push(pdf_p_65);
const pdf_image_66 = {};
pdf_image_66.image = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/14 mesi.png";
pdf_image_66.width = 300;
pdf_image_66.height = 600;
pdf_sect_63["content"].push(pdf_image_66);
pdf_sect_63.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_63);
const pdf_sect_67 = { content: [], styles: {} };
const pdf_p_68 = {};
pdf_p_68.text = [];
pdf_p_68.text.push("Tutti a tavola");
pdf_p_68.style = "titolo1";
pdf_sect_67.content.push(pdf_p_68);
const pdf_p_69 = {};
pdf_p_69.text = [];
pdf_p_69.text.push("17 mesi");
pdf_p_69.style = "titolo2";
pdf_sect_67.content.push(pdf_p_69);
const pdf_image_70 = {};
pdf_image_70.image = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/17 mesi.png";
pdf_image_70.width = 300;
pdf_image_70.height = 600;
pdf_sect_67["content"].push(pdf_image_70);
pdf_sect_67.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_67);
const pdf_sect_71 = { content: [], styles: {} };
const pdf_p_72 = {};
pdf_p_72.text = [];
pdf_p_72.text.push("Tutti a tavola");
pdf_p_72.style = "titolo1";
pdf_sect_71.content.push(pdf_p_72);
const pdf_p_73 = {};
pdf_p_73.text = [];
pdf_p_73.text.push("18 mesi");
pdf_p_73.style = "titolo2";
pdf_sect_71.content.push(pdf_p_73);
const pdf_image_74 = {};
pdf_image_74.image = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/18 mesi.png";
pdf_image_74.width = 300;
pdf_image_74.height = 600;
pdf_sect_71["content"].push(pdf_image_74);
pdf_sect_71.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_71);
const pdf_sect_75 = { content: [], styles: {} };
const pdf_p_76 = {};
pdf_p_76.text = [];
pdf_p_76.text.push("Tutti a tavola");
pdf_p_76.style = "titolo1";
pdf_sect_75.content.push(pdf_p_76);
const pdf_p_77 = {};
pdf_p_77.text = [];
pdf_p_77.text.push("19 mesi");
pdf_p_77.style = "titolo2";
pdf_sect_75.content.push(pdf_p_77);
const pdf_image_78 = {};
pdf_image_78.image = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/19 mesi.png";
pdf_image_78.width = 300;
pdf_image_78.height = 600;
pdf_sect_75["content"].push(pdf_image_78);
pdf_sect_75.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_75);
const pdf_sect_79 = { content: [], styles: {} };
const pdf_p_80 = {};
pdf_p_80.text = [];
pdf_p_80.text.push("Tutti a tavola");
pdf_p_80.style = "titolo1";
pdf_sect_79.content.push(pdf_p_80);
const pdf_p_81 = {};
pdf_p_81.text = [];
pdf_p_81.text.push("5 anni e 9 mesi/1");
pdf_p_81.style = "titolo2";
pdf_sect_79.content.push(pdf_p_81);
const pdf_image_82 = {};
pdf_image_82.image = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/5a 9 m.png";
pdf_image_82.width = 300;
pdf_image_82.height = 600;
pdf_sect_79["content"].push(pdf_image_82);
pdf_sect_79.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_79);
const pdf_sect_83 = { content: [], styles: {} };
const pdf_p_84 = {};
pdf_p_84.text = [];
pdf_p_84.text.push("Tutti a tavola");
pdf_p_84.style = "titolo1";
pdf_sect_83.content.push(pdf_p_84);
const pdf_p_85 = {};
pdf_p_85.text = [];
pdf_p_85.text.push("5 anni e 9 mesi/2");
pdf_p_85.style = "titolo2";
pdf_sect_83.content.push(pdf_p_85);
const pdf_image_86 = {};
pdf_image_86.image = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/5a 9m 2.png";
pdf_image_86.width = 300;
pdf_image_86.height = 600;
pdf_sect_83["content"].push(pdf_image_86);
pdf_sect_83.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_83);
const pdf_sect_87 = { content: [], styles: {} };
const pdf_p_88 = {};
pdf_p_88.text = [];
pdf_p_88.text.push("NpL e NpM");
pdf_p_88.style = "titolo1";
pdf_sect_87.content.push(pdf_p_88);
const pdf_p_89 = {};
pdf_p_89.text = [];
pdf_p_89.text.push("3 anni e 6 mesi, Papà");
pdf_p_89.style = "titolo2";
pdf_sect_87.content.push(pdf_p_89);
const pdf_image_90 = {};
pdf_image_90.image = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/NpL 3a 6m papa.png";
pdf_image_90.width = 300;
pdf_image_90.height = 600;
pdf_sect_87["content"].push(pdf_image_90);
pdf_sect_87.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_87);
const pdf_sect_91 = { content: [], styles: {} };
const pdf_p_92 = {};
pdf_p_92.text = [];
pdf_p_92.text.push("NpL e NpM");
pdf_p_92.style = "titolo1";
pdf_sect_91.content.push(pdf_p_92);
const pdf_p_93 = {};
pdf_p_93.text = [];
pdf_p_93.text.push("4 anni, Dialogico");
pdf_p_93.style = "titolo2";
pdf_sect_91.content.push(pdf_p_93);
const pdf_image_94 = {};
pdf_image_94.image = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/NpL dialogico.png";
pdf_image_94.width = 300;
pdf_image_94.height = 600;
pdf_sect_91["content"].push(pdf_image_94);
pdf_sect_91.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_91);

// Make Pdf

// Build document definition
var now = new Date();
var documentDefinition = pdf_doc_1;
pdf_MainObject.sections.forEach(section => {
    section.content.forEach(contentItem => {
        documentDefinition.content.push(contentItem);
    });
    Object.assign({}, documentDefinition.styles, section.styles);
});

// Dump for test
    fs.writeFileSync("Cosie17marzo2021.json", JSON.stringify(documentDefinition, null, "	"));

// Set fonts
var fonts = {
	Roboto: {
		normal: __dirname + "/fonts/Roboto-Regular.ttf",
		bold: __dirname + "/fonts/Roboto-Medium.ttf",
		italics: __dirname + "/fonts/Roboto-Italic.ttf",
		bolditalics: __dirname + "/fonts/Roboto-MediumItalic.ttf"
	}
};

// Create document
var printer = new pdfmake(fonts);
var pdfDoc = printer.createPdfKitDocument(documentDefinition);
pdfDoc.pipe(fs.createWriteStream(__dirname + "/Cosie17marzo2021.pdf"));
pdfDoc.end();
console.log("DONE written", new Date() - now)
