const fs = require("fs");
const pdfmake = require("pdfmake");

const pdf_doc_1 = { content: [], styles: {} };
const pdf_styleDef_2 = {};
pdf_styleDef_2.fontSize = 60;
pdf_styleDef_2.margin = [0,150,0,0];
pdf_styleDef_2.bold = true;
pdf_doc_1.styles[".forefront-title"] = pdf_styleDef_2;
const pdf_styleDef_3 = {};
pdf_styleDef_3.fontSize = 15;
pdf_styleDef_3.margin = [0,50,0,0];
pdf_doc_1.styles[".forefront-author"] = pdf_styleDef_3;
const pdf_styleDef_4 = {};
pdf_styleDef_4.fontSize = 10;
pdf_styleDef_4.margin = [0,20,0,0];
pdf_styleDef_4.italics = true;
pdf_doc_1.styles[".forefront-date"] = pdf_styleDef_4;
const pdf_styleDef_5 = {};
pdf_styleDef_5.fontSize = 40;
pdf_styleDef_5.bold = true;
pdf_styleDef_5.italics = true;
pdf_styleDef_5.color = "#e02424";
pdf_styleDef_5.alignment = "right";
pdf_styleDef_5.margin = [0,20,0,20];
pdf_doc_1.styles["titolo1"] = pdf_styleDef_5;
const pdf_styleDef_6 = {};
pdf_styleDef_6.fontSize = 30;
pdf_styleDef_6.bold = true;
pdf_styleDef_6.italics = true;
pdf_styleDef_6.color = "#020202";
pdf_styleDef_6.alignment = "left";
pdf_styleDef_6.margin = [0,10,0,10];
pdf_doc_1.styles["titolo2"] = pdf_styleDef_6;
const pdf_styleDef_7 = {};
pdf_styleDef_7.fontSize = 15;
pdf_styleDef_7.alignment = "left";
pdf_styleDef_7.margin = [0,20,0,0];
pdf_doc_1.styles["para1"] = pdf_styleDef_7;
const pdf_styleDef_8 = {};
pdf_styleDef_8.margin = [0,10,0,0];
pdf_doc_1.styles[".cite-reviews"] = pdf_styleDef_8;
const pdf_styleDef_9 = {};
pdf_styleDef_9.fontSize = 10;
pdf_styleDef_9.alignment = "left";
pdf_styleDef_9.bold = true;
pdf_styleDef_9.margin = [0,10,0,0];
pdf_doc_1.styles[".cite-article"] = pdf_styleDef_9;
const pdf_styleDef_10 = {};
pdf_styleDef_10.fontSize = 10;
pdf_styleDef_10.italics = true;
pdf_styleDef_10.alignment = "left";
pdf_doc_1.styles[".cite-authors"] = pdf_styleDef_10;
const pdf_styleDef_11 = {};
pdf_styleDef_11.fontSize = 10;
pdf_styleDef_11.italics = true;
pdf_styleDef_11.alignment = "left";
pdf_doc_1.styles[".cite-review"] = pdf_styleDef_11;
const pdf_styleDef_12 = {};
pdf_styleDef_12.fontSize = 60;
pdf_styleDef_12.margin = [0,100,0,0];
pdf_styleDef_12.alignment = "center";
pdf_styleDef_12.color = "#e02424";
pdf_styleDef_12.bold = true;
pdf_doc_1.styles[".thank-title"] = pdf_styleDef_12;
const pdf_styleDef_13 = {};
pdf_styleDef_13.fontSize = 45;
pdf_styleDef_13.margin = [0,20,0,0];
pdf_styleDef_13.alignment = "center";
pdf_styleDef_13.color = "#e02424";
pdf_doc_1.styles[".thank-subtitle"] = pdf_styleDef_13;
const pdf_sect_14 = { content: [], styles: {} };
const pdf_p_15 = {};
pdf_p_15.text = [];
pdf_p_15.text.push("Le guide anticipatorie");
pdf_p_15.style = ".forefront-title";
pdf_sect_14["content"].push(pdf_p_15);
const pdf_p_16 = {};
pdf_p_16.text = [];
pdf_p_16.text.push("Anna Maria Davoli");
pdf_p_16.style = ".forefront-author";
pdf_sect_14["content"].push(pdf_p_16);
const pdf_p_17 = {};
pdf_p_17.text = [];
pdf_p_17.text.push("17 marzo 2021");
pdf_p_17.style = ".forefront-date";
pdf_sect_14["content"].push(pdf_p_17);
const pdf_MainObject = { sections : [] };
pdf_sect_14.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_14);
const pdf_sect_18 = { content: [], styles: {} };
const pdf_p_19 = {};
pdf_p_19.text = [];
pdf_p_19.text.push("Tutti a tavola");
pdf_p_19.style = "titolo1";
pdf_sect_18["content"].push(pdf_p_19);
const pdf_p_20 = {};
pdf_p_20.text = [];
pdf_p_20.text.push("Le App a supporto di genitori e caregiver");
pdf_p_20.style = "titolo2";
pdf_sect_18["content"].push(pdf_p_20);
const pdf_ul_21 = {};
pdf_ul_21.ul = [];
const pdf_p_22 = {};
pdf_p_22.text = [];
pdf_p_22.text.push("Contenuti basati sulle evidenze");
pdf_p_22.style = "para1";
pdf_ul_21["ul"].push(pdf_p_22);
const pdf_p_23 = {};
pdf_p_23.text = [];
pdf_p_23.text.push("Informazioni coerenti con le linee guida");
pdf_p_23.style = "para1";
pdf_ul_21["ul"].push(pdf_p_23);
const pdf_p_24 = {};
pdf_p_24.text = [];
pdf_p_24.text.push("Sviluppate con il supporto di professionisti sanitari");
pdf_p_24.style = "para1";
pdf_ul_21["ul"].push(pdf_p_24);
const pdf_p_25 = {};
pdf_p_25.text = [];
pdf_p_25.text.push("Con finanziamento adeguato (del Servizio Sanitario)");
pdf_p_25.style = "para1";
pdf_ul_21["ul"].push(pdf_p_25);
pdf_sect_18["content"].push(pdf_ul_21);
const pdf_p_26 = {};
pdf_p_26.text = [];
pdf_p_26.text.push("Garantiscono che ai genitori vengano fornite risorse credibili e affidabili.");
pdf_p_26.style = "para1";
pdf_sect_18["content"].push(pdf_p_26);
const pdf_stack_27 = {};
pdf_stack_27.stack = [];
pdf_stack_27.style = ".cite-reviews";
const pdf_p_28 = {};
pdf_p_28.text = [];
pdf_p_28.text.push("Content and Quality of Infant Feeding Smartphone Apps: Five-Year Update on a Systematic Search and Evaluation");
pdf_p_28.style = ".cite-article";
pdf_stack_27["stack"].push(pdf_p_28);
const pdf_p_29 = {};
pdf_p_29.text = [];
pdf_p_29.text.push("Heilok Cheng, et all");
pdf_p_29.style = ".cite-authors";
pdf_stack_27["stack"].push(pdf_p_29);
const pdf_p_30 = {};
pdf_p_30.text = [];
pdf_p_30.text.push("A Mobile App, KhunLook, to Support Thai Parents and Caregivers With Child Health Supervision: Development, Validation, and Acceptability Study");
pdf_p_30.style = ".cite-article";
pdf_stack_27["stack"].push(pdf_p_30);
const pdf_p_31 = {};
pdf_p_31.text = [];
pdf_p_31.text.push("Rosawan Areemit");
pdf_p_31.style = ".cite-authors";
pdf_stack_27["stack"].push(pdf_p_31);
pdf_sect_18["content"].push(pdf_stack_27);
pdf_sect_18.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_18);
const pdf_sect_32 = { content: [], styles: {} };
const pdf_p_33 = {};
pdf_p_33.text = [];
pdf_p_33.text.push("Tutti a tavola");
pdf_p_33.style = "titolo1";
pdf_sect_32["content"].push(pdf_p_33);
const pdf_p_34 = {};
pdf_p_34.text = [];
pdf_p_34.text.push("Una App aiuta i genitori?");
pdf_p_34.style = "titolo2";
pdf_sect_32["content"].push(pdf_p_34);
const pdf_p_35 = {};
pdf_p_35.text = [];
pdf_p_35.text.push("Un programma eHealth (sanità digitale) di prevenzione dell'obesità infantile incentrato sui genitori può fornire supporto per migliorare l'alimentazione del bambino e l'autoefficacia parentale.");
pdf_p_35.style = "para1";
pdf_sect_32["content"].push(pdf_p_35);
const pdf_p_36 = {};
pdf_p_36.text = [];
pdf_p_36.text.push("Migliora l'alimentazione anche dei genitori.");
pdf_p_36.style = "para1";
pdf_sect_32["content"].push(pdf_p_36);
const pdf_p_37 = {};
pdf_p_37.text = [];
pdf_p_37.text.push("Dal 91,2%  al 97,1% dei genitori che hanno utilizzato l'app può valutare più correttamente i parametri di crescita del proprio bambino.");
pdf_p_37.style = "para1";
pdf_sect_32["content"].push(pdf_p_37);
const pdf_stack_38 = {};
pdf_stack_38.stack = [];
pdf_stack_38.style = ".cite-reviews";
const pdf_p_39 = {};
pdf_p_39.text = [];
pdf_p_39.text.push("A Mobile App, KhunLook, to Support Thai Parents and Caregivers With Child Health Supervision: Development, Validation, and Acceptability Study");
pdf_p_39.style = ".cite-article";
pdf_stack_38["stack"].push(pdf_p_39);
const pdf_p_40 = {};
pdf_p_40.text = [];
pdf_p_40.text.push("Rosawan Areemit et all");
pdf_p_40.style = ".cite-authors";
pdf_stack_38["stack"].push(pdf_p_40);
const pdf_p_41 = {};
pdf_p_41.text = [];
pdf_p_41.text.push("An Internet-Based Childhood Obesity Prevention Program (Time2bHealthy) for Parents of Preschool-Aged Children.");
pdf_p_41.style = ".cite-article";
pdf_stack_38["stack"].push(pdf_p_41);
const pdf_p_42 = {};
pdf_p_42.text = [];
pdf_p_42.text.push("Megan L Hammersley et all");
pdf_p_42.style = ".cite-authors";
pdf_stack_38["stack"].push(pdf_p_42);
const pdf_p_43 = {};
pdf_p_43.text = [];
pdf_p_43.text.push("Randomized Controlled Trial J Med Internet Res, 2019 Feb 8;21(2):e11964. Doi: 10.2196/11964.");
pdf_p_43.style = ".cite-review";
pdf_stack_38["stack"].push(pdf_p_43);
const pdf_p_44 = {};
pdf_p_44.text = [];
pdf_p_44.text.push("A systematic evaluation of digital nutrition promotion websites and apps for supporting parents to influence children’s nutrition");
pdf_p_44.style = ".cite-article";
pdf_stack_38["stack"].push(pdf_p_44);
const pdf_p_45 = {};
pdf_p_45.text = [];
pdf_p_45.text.push("Dorota Zarnowiecki, et all");
pdf_p_45.style = ".cite-authors";
pdf_stack_38["stack"].push(pdf_p_45);
const pdf_p_46 = {};
pdf_p_46.text = [];
pdf_p_46.text.push("International Journal of Behavioral Nutrition and Physical Activity volume 17, Article number: 17 (2020)");
pdf_p_46.style = ".cite-review";
pdf_stack_38["stack"].push(pdf_p_46);
pdf_sect_32["content"].push(pdf_stack_38);
pdf_sect_32.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_32);
const pdf_sect_47 = { content: [], styles: {} };
const pdf_p_48 = {};
pdf_p_48.text = [];
pdf_p_48.text.push("Tutti a tavola");
pdf_p_48.style = "titolo1";
pdf_sect_47["content"].push(pdf_p_48);
const pdf_p_49 = {};
pdf_p_49.text = [];
pdf_p_49.text.push("La App BeBa");
pdf_p_49.style = "titolo2";
pdf_sect_47["content"].push(pdf_p_49);
const pdf_p_50 = {};
pdf_p_50.text = [];
pdf_p_50.text.push("La App si propone l'obiettivo di essere uno stimolo per le famiglie per contrastare l'obesità infantile.");
pdf_p_50.style = "para1";
pdf_sect_47["content"].push(pdf_p_50);
const pdf_p_51 = {};
pdf_p_51.text = [];
pdf_p_51.text.push("La guida Tutti a tavola ha la responsabilità di fornire indicazioni basate sulle evidenze disponibili, ma anche la necessità di essere condivisa dai pediatri in modo che i contenuti vengano supportati dall'invito a scaricarla e usarla quale accompagnamento alle parole del Pediatra.");
pdf_p_51.style = "para1";
pdf_sect_47["content"].push(pdf_p_51);
const pdf_p_52 = {};
pdf_p_52.text = [];
pdf_p_52.text.push("Sarebbe davvero sgradevole che quello che trovano scritto i genitori contrastasse con i suggerimenti del pediatra.");
pdf_p_52.style = "para1";
pdf_sect_47["content"].push(pdf_p_52);
const pdf_p_53 = {};
pdf_p_53.text = [];
pdf_p_53.text.push("Non vi è nulla di prescrittivo, ma quando parliamo di allattamento  e di alimentazione complementare i tempi e le modalità, se non condivise devono offrire al genitore una spiegazione soddisfacente che non si ponga in contrasto con i contenuti delle guide.");
pdf_p_53.style = "para1";
pdf_sect_47["content"].push(pdf_p_53);
pdf_sect_47.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_47);
const pdf_sect_54 = { content: [], styles: {} };
const pdf_p_55 = {};
pdf_p_55.text = [];
pdf_p_55.text.push("Tutti a tavola");
pdf_p_55.style = "titolo1";
pdf_sect_54["content"].push(pdf_p_55);
const pdf_p_56 = {};
pdf_p_56.text = [];
pdf_p_56.text.push("nascita");
pdf_p_56.style = "titolo2";
pdf_sect_54["content"].push(pdf_p_56);
const pdf_image_57 = {};
pdf_image_57.image = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/nascita.png";
pdf_image_57.width = 300;
pdf_image_57.height = 550;
pdf_sect_54["content"].push(pdf_image_57);
pdf_sect_54.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_54);
const pdf_sect_58 = { content: [], styles: {} };
const pdf_p_59 = {};
pdf_p_59.text = [];
pdf_p_59.text.push("Tutti a tavola");
pdf_p_59.style = "titolo1";
pdf_sect_58["content"].push(pdf_p_59);
const pdf_p_60 = {};
pdf_p_60.text = [];
pdf_p_60.text.push("15 giorni");
pdf_p_60.style = "titolo2";
pdf_sect_58["content"].push(pdf_p_60);
const pdf_image_61 = {};
pdf_image_61.image = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/15 giorni.png";
pdf_image_61.width = 300;
pdf_image_61.height = 550;
pdf_sect_58["content"].push(pdf_image_61);
pdf_sect_58.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_58);
const pdf_sect_62 = { content: [], styles: {} };
const pdf_p_63 = {};
pdf_p_63.text = [];
pdf_p_63.text.push("Tutti a tavola");
pdf_p_63.style = "titolo1";
pdf_sect_62["content"].push(pdf_p_63);
const pdf_p_64 = {};
pdf_p_64.text = [];
pdf_p_64.text.push("1 mese");
pdf_p_64.style = "titolo2";
pdf_sect_62["content"].push(pdf_p_64);
const pdf_image_65 = {};
pdf_image_65.image = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/1 mese.png";
pdf_image_65.width = 300;
pdf_image_65.height = 550;
pdf_sect_62["content"].push(pdf_image_65);
pdf_sect_62.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_62);
const pdf_sect_66 = { content: [], styles: {} };
const pdf_p_67 = {};
pdf_p_67.text = [];
pdf_p_67.text.push("Tutti a tavola");
pdf_p_67.style = "titolo1";
pdf_sect_66["content"].push(pdf_p_67);
const pdf_p_68 = {};
pdf_p_68.text = [];
pdf_p_68.text.push("5 mesi");
pdf_p_68.style = "titolo2";
pdf_sect_66["content"].push(pdf_p_68);
const pdf_image_69 = {};
pdf_image_69.image = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/5 mesi.png";
pdf_image_69.width = 300;
pdf_image_69.height = 550;
pdf_sect_66["content"].push(pdf_image_69);
pdf_sect_66.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_66);
const pdf_sect_70 = { content: [], styles: {} };
const pdf_p_71 = {};
pdf_p_71.text = [];
pdf_p_71.text.push("Tutti a tavola");
pdf_p_71.style = "titolo1";
pdf_sect_70["content"].push(pdf_p_71);
const pdf_p_72 = {};
pdf_p_72.text = [];
pdf_p_72.text.push("6 mesi");
pdf_p_72.style = "titolo2";
pdf_sect_70["content"].push(pdf_p_72);
const pdf_image_73 = {};
pdf_image_73.image = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/6 mesi.png";
pdf_image_73.width = 300;
pdf_image_73.height = 550;
pdf_sect_70["content"].push(pdf_image_73);
pdf_sect_70.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_70);
const pdf_sect_74 = { content: [], styles: {} };
const pdf_p_75 = {};
pdf_p_75.text = [];
pdf_p_75.text.push("Tutti a tavola");
pdf_p_75.style = "titolo1";
pdf_sect_74["content"].push(pdf_p_75);
const pdf_p_76 = {};
pdf_p_76.text = [];
pdf_p_76.text.push("9 mesi/1");
pdf_p_76.style = "titolo2";
pdf_sect_74["content"].push(pdf_p_76);
const pdf_image_77 = {};
pdf_image_77.image = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/9 mesi 1.png";
pdf_image_77.width = 300;
pdf_image_77.height = 550;
pdf_sect_74["content"].push(pdf_image_77);
pdf_sect_74.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_74);
const pdf_sect_78 = { content: [], styles: {} };
const pdf_p_79 = {};
pdf_p_79.text = [];
pdf_p_79.text.push("Tutti a tavola");
pdf_p_79.style = "titolo1";
pdf_sect_78["content"].push(pdf_p_79);
const pdf_p_80 = {};
pdf_p_80.text = [];
pdf_p_80.text.push("9 mesi/2");
pdf_p_80.style = "titolo2";
pdf_sect_78["content"].push(pdf_p_80);
const pdf_image_81 = {};
pdf_image_81.image = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/9 mesi 2.png";
pdf_image_81.width = 300;
pdf_image_81.height = 550;
pdf_sect_78["content"].push(pdf_image_81);
pdf_sect_78.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_78);
const pdf_sect_82 = { content: [], styles: {} };
const pdf_p_83 = {};
pdf_p_83.text = [];
pdf_p_83.text.push("Tutti a tavola");
pdf_p_83.style = "titolo1";
pdf_sect_82["content"].push(pdf_p_83);
const pdf_p_84 = {};
pdf_p_84.text = [];
pdf_p_84.text.push("1 anno");
pdf_p_84.style = "titolo2";
pdf_sect_82["content"].push(pdf_p_84);
const pdf_image_85 = {};
pdf_image_85.image = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/1 anno.png";
pdf_image_85.width = 300;
pdf_image_85.height = 550;
pdf_sect_82["content"].push(pdf_image_85);
pdf_sect_82.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_82);
const pdf_sect_86 = { content: [], styles: {} };
const pdf_p_87 = {};
pdf_p_87.text = [];
pdf_p_87.text.push("Tutti a tavola");
pdf_p_87.style = "titolo1";
pdf_sect_86["content"].push(pdf_p_87);
const pdf_p_88 = {};
pdf_p_88.text = [];
pdf_p_88.text.push("14 mesi");
pdf_p_88.style = "titolo2";
pdf_sect_86["content"].push(pdf_p_88);
const pdf_image_89 = {};
pdf_image_89.image = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/14 mesi.png";
pdf_image_89.width = 300;
pdf_image_89.height = 550;
pdf_sect_86["content"].push(pdf_image_89);
pdf_sect_86.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_86);
const pdf_sect_90 = { content: [], styles: {} };
const pdf_p_91 = {};
pdf_p_91.text = [];
pdf_p_91.text.push("Tutti a tavola");
pdf_p_91.style = "titolo1";
pdf_sect_90["content"].push(pdf_p_91);
const pdf_p_92 = {};
pdf_p_92.text = [];
pdf_p_92.text.push("17 mesi");
pdf_p_92.style = "titolo2";
pdf_sect_90["content"].push(pdf_p_92);
const pdf_image_93 = {};
pdf_image_93.image = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/17 mesi.png";
pdf_image_93.width = 300;
pdf_image_93.height = 550;
pdf_sect_90["content"].push(pdf_image_93);
pdf_sect_90.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_90);
const pdf_sect_94 = { content: [], styles: {} };
const pdf_p_95 = {};
pdf_p_95.text = [];
pdf_p_95.text.push("Tutti a tavola");
pdf_p_95.style = "titolo1";
pdf_sect_94["content"].push(pdf_p_95);
const pdf_p_96 = {};
pdf_p_96.text = [];
pdf_p_96.text.push("18 mesi");
pdf_p_96.style = "titolo2";
pdf_sect_94["content"].push(pdf_p_96);
const pdf_image_97 = {};
pdf_image_97.image = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/18 mesi.png";
pdf_image_97.width = 300;
pdf_image_97.height = 550;
pdf_sect_94["content"].push(pdf_image_97);
pdf_sect_94.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_94);
const pdf_sect_98 = { content: [], styles: {} };
const pdf_p_99 = {};
pdf_p_99.text = [];
pdf_p_99.text.push("Tutti a tavola");
pdf_p_99.style = "titolo1";
pdf_sect_98["content"].push(pdf_p_99);
const pdf_p_100 = {};
pdf_p_100.text = [];
pdf_p_100.text.push("19 mesi");
pdf_p_100.style = "titolo2";
pdf_sect_98["content"].push(pdf_p_100);
const pdf_image_101 = {};
pdf_image_101.image = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/19 mesi.png";
pdf_image_101.width = 300;
pdf_image_101.height = 550;
pdf_sect_98["content"].push(pdf_image_101);
pdf_sect_98.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_98);
const pdf_sect_102 = { content: [], styles: {} };
const pdf_p_103 = {};
pdf_p_103.text = [];
pdf_p_103.text.push("Tutti a tavola");
pdf_p_103.style = "titolo1";
pdf_sect_102["content"].push(pdf_p_103);
const pdf_p_104 = {};
pdf_p_104.text = [];
pdf_p_104.text.push("5 anni e 9 mesi/1");
pdf_p_104.style = "titolo2";
pdf_sect_102["content"].push(pdf_p_104);
const pdf_image_105 = {};
pdf_image_105.image = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/5a 9 m.png";
pdf_image_105.width = 300;
pdf_image_105.height = 550;
pdf_sect_102["content"].push(pdf_image_105);
pdf_sect_102.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_102);
const pdf_sect_106 = { content: [], styles: {} };
const pdf_p_107 = {};
pdf_p_107.text = [];
pdf_p_107.text.push("Tutti a tavola");
pdf_p_107.style = "titolo1";
pdf_sect_106["content"].push(pdf_p_107);
const pdf_p_108 = {};
pdf_p_108.text = [];
pdf_p_108.text.push("5 anni e 9 mesi/2");
pdf_p_108.style = "titolo2";
pdf_sect_106["content"].push(pdf_p_108);
const pdf_image_109 = {};
pdf_image_109.image = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/5a 9m 2.png";
pdf_image_109.width = 300;
pdf_image_109.height = 550;
pdf_sect_106["content"].push(pdf_image_109);
pdf_sect_106.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_106);
const pdf_sect_110 = { content: [], styles: {} };
const pdf_p_111 = {};
pdf_p_111.text = [];
pdf_p_111.text.push("NpL e NpM");
pdf_p_111.style = "titolo1";
pdf_sect_110["content"].push(pdf_p_111);
const pdf_p_112 = {};
pdf_p_112.text = [];
pdf_p_112.text.push("3 anni e 6 mesi, Papà");
pdf_p_112.style = "titolo2";
pdf_sect_110["content"].push(pdf_p_112);
const pdf_image_113 = {};
pdf_image_113.image = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/NpL 3a 6m papa.png";
pdf_image_113.width = 300;
pdf_image_113.height = 550;
pdf_sect_110["content"].push(pdf_image_113);
pdf_sect_110.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_110);
const pdf_sect_114 = { content: [], styles: {} };
const pdf_p_115 = {};
pdf_p_115.text = [];
pdf_p_115.text.push("NpL e NpM");
pdf_p_115.style = "titolo1";
pdf_sect_114["content"].push(pdf_p_115);
const pdf_p_116 = {};
pdf_p_116.text = [];
pdf_p_116.text.push("4 anni, Dialogico");
pdf_p_116.style = "titolo2";
pdf_sect_114["content"].push(pdf_p_116);
const pdf_image_117 = {};
pdf_image_117.image = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/NpL dialogico.png";
pdf_image_117.width = 300;
pdf_image_117.height = 550;
pdf_sect_114["content"].push(pdf_image_117);
pdf_sect_114.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_114);
const pdf_sect_118 = { content: [], styles: {} };
const pdf_p_119 = {};
pdf_p_119.text = [];
pdf_p_119.text.push(" ");
pdf_p_119.style = "titolo1";
pdf_sect_118["content"].push(pdf_p_119);
const pdf_p_120 = {};
pdf_p_120.text = [];
pdf_p_120.text.push(" ");
pdf_p_120.style = "titolo2";
pdf_sect_118["content"].push(pdf_p_120);
const pdf_image_121 = {};
pdf_image_121.image = "C:/My/wizzi/stfnbssl/stfnbssl.github.io/cosie/.wizzi/src/17marzo2021/images/Fine.png";
pdf_image_121.width = 300;
pdf_image_121.height = 550;
pdf_sect_118["content"].push(pdf_image_121);
pdf_sect_118.content.push({ text: ' ', pageBreak: 'after'});
pdf_MainObject.sections.push(pdf_sect_118);

// Make Pdf

// Build document definition
var now = new Date();
var documentDefinition = pdf_doc_1;
pdf_MainObject.sections.forEach(section => {
    section.content.forEach(contentItem => {
        documentDefinition.content.push(contentItem);
    });
    Object.assign({}, documentDefinition.styles, section.styles);
});

// Dump for test
    fs.writeFileSync(__dirname + "/Cosie17marzo2021.json", JSON.stringify(documentDefinition, null, "	"));

// Set fonts
var fonts = {
	Roboto: {
		normal: __dirname + "/fonts/Roboto-Regular.ttf",
		bold: __dirname + "/fonts/Roboto-Medium.ttf",
		italics: __dirname + "/fonts/Roboto-Italic.ttf",
		bolditalics: __dirname + "/fonts/Roboto-MediumItalic.ttf"
	}
};

// Create document
var printer = new pdfmake(fonts);
var pdfDoc = printer.createPdfKitDocument(documentDefinition);
pdfDoc.pipe(fs.createWriteStream(__dirname + "/Cosie17marzo2021.pdf"));
pdfDoc.end();
console.log("DONE written", new Date() - now)
